FROM nvcr.io/nvidia/tensorrt:24.02-py3
RUN sed -i "s|http://archive.ubuntu.com/ubuntu/|http://mirrors.tuna.tsinghua.edu.cn/ubuntu/|g" /etc/apt/sources.list && \
    sed -i "s|http://security.ubuntu.com/ubuntu/|http://mirrors.tuna.tsinghua.edu.cn/ubuntu/|g" /etc/apt/sources.list
RUN apt-get update && apt-get install -y build-essential ffmpeg git gstreamer1.0-plugins-base gstreamer1.0-plugins-good libavcodec-dev libavformat-dev libglib2.0-0 libgl1-mesa-dev libgl1-mesa-glx libgstreamer1.0-0 libmtdev1 libportmidi-dev libpulse0 libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libswscale-dev libzip-dev ocl-icd-opencl-dev opencl-headers pkg-config python3-dev python3-pip zlib1g-dev && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY . /app
RUN python3 -m pip install --trusted-host pypi.tuna.tsinghua.edu.cn -i https://pypi.tuna.tsinghua.edu.cn/simple --upgrade pip && \
    python3 -m pip install --trusted-host pypi.tuna.tsinghua.edu.cn -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements-web.txt -r requirements-desktop.txt
ENV PYTHONPATH=/app
EXPOSE 8001
CMD ["python3", "-m", "katrain", "--ui", "web", "--host", "0.0.0.0", "--port", "8001"]
