#!/usr/bin/env python3
"""
Batch translation script for KaTrain Galaxy UI.
Updates all language files with proper translations for Galaxy UI keys.

Usage:
    python scripts/batch_translate_galaxy.py

Requirements:
    pip install polib
"""

import os
import polib
from pathlib import Path

# Project paths
PROJECT_ROOT = Path(__file__).parent.parent
I18N_DIR = PROJECT_ROOT / "katrain" / "i18n" / "locales"

# All Galaxy UI translation keys with translations for each language
# Format: {msgid: {lang_code: msgstr}}
GALAXY_TRANSLATIONS = {
    # Dashboard
    "dashboard:welcome": {
        "en": "Welcome to Galaxy Go",
        "cn": "欢迎来到 Galaxy Go",
        "tw": "歡迎來到 Galaxy Go",
        "jp": "Galaxy Goへようこそ",
        "ko": "Galaxy Go에 오신 것을 환영합니다",
        "de": "Willkommen bei Galaxy Go",
        "es": "Bienvenido a Galaxy Go",
        "fr": "Bienvenue sur Galaxy Go",
        "ru": "Добро пожаловать в Galaxy Go",
        "tr": "Galaxy Go'ya Hoş Geldiniz",
        "ua": "Ласкаво просимо до Galaxy Go",
    },
    "dashboard:tagline": {
        "en": "Your professional Go training and analysis platform.",
        "cn": "您的专业围棋训练与分析平台。",
        "tw": "您的專業圍棋訓練與分析平台。",
        "jp": "プロフェッショナルな囲碁トレーニング＆分析プラットフォーム。",
        "ko": "전문적인 바둑 훈련 및 분석 플랫폼.",
        "de": "Ihre professionelle Go-Trainings- und Analyseplattform.",
        "es": "Tu plataforma profesional de entrenamiento y análisis de Go.",
        "fr": "Votre plateforme professionnelle d'entraînement et d'analyse de Go.",
        "ru": "Ваша профессиональная платформа для обучения и анализа игры в Го.",
        "tr": "Profesyonel Go eğitim ve analiz platformunuz.",
        "ua": "Ваша професійна платформа для навчання та аналізу гри в Го.",
    },
    "dashboard:play_desc": {
        "en": "Challenge AI opponents or play against friends. Features Rated games to establish your rank.",
        "cn": "挑战AI对手或与朋友对弈。支持升降级对局以确定您的等级。",
        "tw": "挑戰AI對手或與朋友對弈。支持升降級對局以確定您的等級。",
        "jp": "AIと対戦したり、友達と対戦したりできます。レート戦で段位を確立できます。",
        "ko": "AI 상대와 대결하거나 친구와 대국하세요. 레이팅 게임으로 등급을 확립하세요.",
        "de": "Fordern Sie KI-Gegner heraus oder spielen Sie gegen Freunde. Ranglistenspiele zur Bestimmung Ihres Ranges.",
        "es": "Desafía a oponentes de IA o juega contra amigos. Partidas clasificatorias para establecer tu rango.",
        "fr": "Affrontez des adversaires IA ou jouez contre des amis. Parties classées pour établir votre rang.",
        "ru": "Играйте против ИИ или друзей. Рейтинговые игры для определения вашего ранга.",
        "tr": "Yapay zeka rakiplerine meydan okuyun veya arkadaşlarınızla oynayın. Derecenizi belirlemek için dereceli oyunlar.",
        "ua": "Грайте проти ШІ або друзів. Рейтингові ігри для визначення вашого рангу.",
    },
    "dashboard:research_desc": {
        "en": "Analyze games with AI, explore variations, and manage your SGF library.",
        "cn": "使用AI分析棋谱，探索变化，管理您的SGF棋谱库。",
        "tw": "使用AI分析棋譜，探索變化，管理您的SGF棋譜庫。",
        "jp": "AIでゲームを分析し、変化を探索し、SGFライブラリを管理します。",
        "ko": "AI로 기보를 분석하고, 변화를 탐색하고, SGF 라이브러리를 관리하세요.",
        "de": "Analysieren Sie Spiele mit KI, erkunden Sie Variationen und verwalten Sie Ihre SGF-Bibliothek.",
        "es": "Analiza partidas con IA, explora variaciones y gestiona tu biblioteca SGF.",
        "fr": "Analysez des parties avec l'IA, explorez les variations et gérez votre bibliothèque SGF.",
        "ru": "Анализируйте игры с помощью ИИ, исследуйте варианты и управляйте библиотекой SGF.",
        "tr": "Yapay zeka ile oyunları analiz edin, varyasyonları keşfedin ve SGF kütüphanenizi yönetin.",
        "ua": "Аналізуйте ігри з ШІ, досліджуйте варіанти та керуйте бібліотекою SGF.",
    },
    "dashboard:report_desc": {
        "en": "Detailed game reports and style analysis. (Coming Soon)",
        "cn": "详细的对局报告和风格分析。(即将推出)",
        "tw": "詳細的對局報告和風格分析。(即將推出)",
        "jp": "詳細なゲームレポートとスタイル分析。（近日公開）",
        "ko": "상세한 게임 리포트와 스타일 분석. (곧 출시)",
        "de": "Detaillierte Spielberichte und Stilanalyse. (Demnächst)",
        "es": "Informes detallados de partidas y análisis de estilo. (Próximamente)",
        "fr": "Rapports de parties détaillés et analyse de style. (Bientôt disponible)",
        "ru": "Подробные отчеты об играх и анализ стиля. (Скоро)",
        "tr": "Ayrıntılı oyun raporları ve stil analizi. (Yakında)",
        "ua": "Детальні звіти про ігри та аналіз стилю. (Незабаром)",
    },
    "dashboard:live_desc": {
        "en": "Watch top games and live tournaments. (Coming Soon)",
        "cn": "观看顶级对局和现场锦标赛。(即将推出)",
        "tw": "觀看頂級對局和現場錦標賽。(即將推出)",
        "jp": "トップゲームやライブトーナメントを観戦。（近日公開）",
        "ko": "최고 수준의 대국과 실시간 대회 관전. (곧 출시)",
        "de": "Top-Spiele und Live-Turniere ansehen. (Demnächst)",
        "es": "Ver partidas de alto nivel y torneos en vivo. (Próximamente)",
        "fr": "Regardez les meilleures parties et tournois en direct. (Bientôt disponible)",
        "ru": "Смотрите лучшие игры и турниры в прямом эфире. (Скоро)",
        "tr": "En iyi oyunları ve canlı turnuvaları izleyin. (Yakında)",
        "ua": "Дивіться топові ігри та турніри в прямому ефірі. (Незабаром)",
    },

    # Sidebar / Navigation
    "Settings": {
        "en": "Settings",
        "cn": "设置",
        "tw": "設定",
        "jp": "設定",
        "ko": "설정",
        "de": "Einstellungen",
        "es": "Configuración",
        "fr": "Paramètres",
        "ru": "Настройки",
        "tr": "Ayarlar",
        "ua": "Налаштування",
    },
    "Research": {
        "en": "Research",
        "cn": "研究",
        "tw": "研究",
        "jp": "研究",
        "ko": "연구",
        "de": "Forschung",
        "es": "Investigación",
        "fr": "Recherche",
        "ru": "Исследование",
        "tr": "Araştırma",
        "ua": "Дослідження",
    },
    "Live": {
        "en": "Live",
        "cn": "直播",
        "tw": "直播",
        "jp": "ライブ",
        "ko": "라이브",
        "de": "Live",
        "es": "En vivo",
        "fr": "En direct",
        "ru": "Прямой эфир",
        "tr": "Canlı",
        "ua": "Наживо",
    },
    "Login": {
        "en": "Sign In",
        "cn": "登录",
        "tw": "登入",
        "jp": "ログイン",
        "ko": "로그인",
        "de": "Anmelden",
        "es": "Iniciar sesión",
        "fr": "Connexion",
        "ru": "Войти",
        "tr": "Giriş Yap",
        "ua": "Увійти",
    },
    "Language": {
        "en": "Language",
        "cn": "语言",
        "tw": "語言",
        "jp": "言語",
        "ko": "언어",
        "de": "Sprache",
        "es": "Idioma",
        "fr": "Langue",
        "ru": "Язык",
        "tr": "Dil",
        "ua": "Мова",
    },

    # Play Menu
    "play:choose_mode": {
        "en": "Choose your game mode",
        "cn": "选择游戏模式",
        "tw": "選擇遊戲模式",
        "jp": "ゲームモードを選択",
        "ko": "게임 모드 선택",
        "de": "Wählen Sie Ihren Spielmodus",
        "es": "Elige tu modo de juego",
        "fr": "Choisissez votre mode de jeu",
        "ru": "Выберите режим игры",
        "tr": "Oyun modunuzu seçin",
        "ua": "Оберіть режим гри",
    },
    "play:vs_ai_free": {
        "en": "Play vs AI (Free)",
        "cn": "自由对弈",
        "tw": "自由對弈",
        "jp": "AI対戦（フリー）",
        "ko": "AI 대국 (자유)",
        "de": "Gegen KI spielen (Frei)",
        "es": "Jugar vs IA (Libre)",
        "fr": "Jouer contre l'IA (Libre)",
        "ru": "Играть против ИИ (Свободная)",
        "tr": "Yapay Zekaya Karşı Oyna (Serbest)",
        "ua": "Грати проти ШІ (Вільна)",
    },
    "play:vs_ai_free_desc": {
        "en": "Practice with full analysis, undo, and custom settings.",
        "cn": "练习模式，支持完整分析、悔棋和自定义设置。",
        "tw": "練習模式，支持完整分析、悔棋和自定義設定。",
        "jp": "完全な分析、待った、カスタム設定で練習できます。",
        "ko": "완전한 분석, 되돌리기, 사용자 설정으로 연습하세요.",
        "de": "Üben Sie mit vollständiger Analyse, Rückgängig und benutzerdefinierten Einstellungen.",
        "es": "Practica con análisis completo, deshacer y configuración personalizada.",
        "fr": "Entraînez-vous avec analyse complète, annulation et paramètres personnalisés.",
        "ru": "Практикуйтесь с полным анализом, отменой хода и настройками.",
        "tr": "Tam analiz, geri alma ve özel ayarlarla pratik yapın.",
        "ua": "Практикуйтесь з повним аналізом, скасуванням ходу та налаштуваннями.",
    },
    "play:rated_ai": {
        "en": "Rated Game vs AI",
        "cn": "升降级对局",
        "tw": "升降級對局",
        "jp": "レート戦 vs AI",
        "ko": "레이팅 대국 vs AI",
        "de": "Ranglistenspiel gegen KI",
        "es": "Partida clasificatoria vs IA",
        "fr": "Partie classée vs IA",
        "ru": "Рейтинговая игра против ИИ",
        "tr": "Dereceli Oyun vs Yapay Zeka",
        "ua": "Рейтингова гра проти ШІ",
    },
    "play:rated_ai_desc": {
        "en": "Play a ranked game against a human-like AI. No analysis during game.",
        "cn": "与拟人AI进行排位赛。对局中无分析功能。",
        "tw": "與擬人AI進行排位賽。對局中無分析功能。",
        "jp": "人間らしいAIとランク戦をプレイ。ゲーム中の分析はありません。",
        "ko": "인간형 AI와 랭크 대국. 대국 중 분석 없음.",
        "de": "Spielen Sie ein Ranglistenspiel gegen eine menschenähnliche KI. Keine Analyse während des Spiels.",
        "es": "Juega una partida clasificatoria contra una IA similar a humanos. Sin análisis durante la partida.",
        "fr": "Jouez une partie classée contre une IA humanoïde. Pas d'analyse pendant la partie.",
        "ru": "Играйте рейтинговую игру против человекоподобного ИИ. Без анализа во время игры.",
        "tr": "İnsan benzeri bir yapay zekaya karşı dereceli oyun oynayın. Oyun sırasında analiz yok.",
        "ua": "Грайте рейтингову гру проти людиноподібного ШІ. Без аналізу під час гри.",
    },
    "play:hvh": {
        "en": "Human vs Human",
        "cn": "人人对弈",
        "tw": "人人對弈",
        "jp": "人間対人間",
        "ko": "인간 대 인간",
        "de": "Mensch gegen Mensch",
        "es": "Humano vs Humano",
        "fr": "Humain contre Humain",
        "ru": "Человек против человека",
        "tr": "İnsan vs İnsan",
        "ua": "Людина проти людини",
    },
    "play:hvh_desc": {
        "en": "Challenge a friend or find an opponent online.",
        "cn": "挑战好友或在线匹配对手。",
        "tw": "挑戰好友或在線匹配對手。",
        "jp": "友達に挑戦するか、オンラインで対戦相手を見つけましょう。",
        "ko": "친구에게 도전하거나 온라인에서 상대를 찾으세요.",
        "de": "Fordern Sie einen Freund heraus oder finden Sie einen Gegner online.",
        "es": "Desafía a un amigo o encuentra un oponente en línea.",
        "fr": "Défiez un ami ou trouvez un adversaire en ligne.",
        "ru": "Бросьте вызов другу или найдите соперника онлайн.",
        "tr": "Bir arkadaşınıza meydan okuyun veya çevrimiçi rakip bulun.",
        "ua": "Киньте виклик другу або знайдіть суперника онлайн.",
    },

    # AI Setup Page
    "play:free_play_setup": {
        "en": "Free Play Setup",
        "cn": "自由对弈设置",
        "tw": "自由對弈設定",
        "jp": "フリープレイ設定",
        "ko": "자유 대국 설정",
        "de": "Freispiel-Einstellungen",
        "es": "Configuración de juego libre",
        "fr": "Configuration du jeu libre",
        "ru": "Настройка свободной игры",
        "tr": "Serbest Oyun Ayarları",
        "ua": "Налаштування вільної гри",
    },
    "play:rated_ai_setup": {
        "en": "Rated AI Game Setup",
        "cn": "升降级对局设置",
        "tw": "升降級對局設定",
        "jp": "レート戦設定",
        "ko": "레이팅 대국 설정",
        "de": "Ranglistenspiel-Einstellungen",
        "es": "Configuración de partida clasificatoria",
        "fr": "Configuration de partie classée",
        "ru": "Настройка рейтинговой игры",
        "tr": "Dereceli Oyun Ayarları",
        "ua": "Налаштування рейтингової гри",
    },
    "Board & Rules": {
        "en": "Board & Rules",
        "cn": "棋盘与规则",
        "tw": "棋盤與規則",
        "jp": "盤面とルール",
        "ko": "바둑판 및 규칙",
        "de": "Brett & Regeln",
        "es": "Tablero y reglas",
        "fr": "Plateau et règles",
        "ru": "Доска и правила",
        "tr": "Tahta ve Kurallar",
        "ua": "Дошка та правила",
    },
    "Opponent & Time": {
        "en": "Opponent & Time",
        "cn": "对手与时间",
        "tw": "對手與時間",
        "jp": "対戦相手と時間",
        "ko": "상대 및 시간",
        "de": "Gegner & Zeit",
        "es": "Oponente y tiempo",
        "fr": "Adversaire et temps",
        "ru": "Соперник и время",
        "tr": "Rakip ve Süre",
        "ua": "Суперник та час",
    },
    "Your Color": {
        "en": "Your Color",
        "cn": "执子颜色",
        "tw": "執子顏色",
        "jp": "あなたの色",
        "ko": "당신의 색",
        "de": "Ihre Farbe",
        "es": "Tu color",
        "fr": "Votre couleur",
        "ru": "Ваш цвет",
        "tr": "Sizin Renginiz",
        "ua": "Ваш колір",
    },
    "Black": {
        "en": "Black",
        "cn": "黑棋",
        "tw": "黑棋",
        "jp": "黒",
        "ko": "흑",
        "de": "Schwarz",
        "es": "Negro",
        "fr": "Noir",
        "ru": "Черные",
        "tr": "Siyah",
        "ua": "Чорні",
    },
    "White": {
        "en": "White",
        "cn": "白棋",
        "tw": "白棋",
        "jp": "白",
        "ko": "백",
        "de": "Weiß",
        "es": "Blanco",
        "fr": "Blanc",
        "ru": "Белые",
        "tr": "Beyaz",
        "ua": "Білі",
    },
    "First": {
        "en": "First",
        "cn": "先手",
        "tw": "先手",
        "jp": "先手",
        "ko": "선수",
        "de": "Erster",
        "es": "Primero",
        "fr": "Premier",
        "ru": "Первый",
        "tr": "İlk",
        "ua": "Перший",
    },
    "Second": {
        "en": "Second",
        "cn": "后手",
        "tw": "後手",
        "jp": "後手",
        "ko": "후수",
        "de": "Zweiter",
        "es": "Segundo",
        "fr": "Second",
        "ru": "Второй",
        "tr": "İkinci",
        "ua": "Другий",
    },
    "Enable Timer": {
        "en": "Enable Timer",
        "cn": "启用计时器",
        "tw": "啟用計時器",
        "jp": "タイマーを有効にする",
        "ko": "타이머 활성화",
        "de": "Timer aktivieren",
        "es": "Habilitar temporizador",
        "fr": "Activer le chronomètre",
        "ru": "Включить таймер",
        "tr": "Zamanlayıcıyı Etkinleştir",
        "ua": "Увімкнути таймер",
    },
    "Rank": {
        "en": "Rank",
        "cn": "段位",
        "tw": "段位",
        "jp": "段位",
        "ko": "급수",
        "de": "Rang",
        "es": "Rango",
        "fr": "Rang",
        "ru": "Ранг",
        "tr": "Derece",
        "ua": "Ранг",
    },
    "Standard": {
        "en": "Standard",
        "cn": "标准",
        "tw": "標準",
        "jp": "標準",
        "ko": "표준",
        "de": "Standard",
        "es": "Estándar",
        "fr": "Standard",
        "ru": "Стандартный",
        "tr": "Standart",
        "ua": "Стандартний",
    },
    "Stones": {
        "en": "Stones",
        "cn": "让子",
        "tw": "讓子",
        "jp": "子",
        "ko": "돌",
        "de": "Steine",
        "es": "Piedras",
        "fr": "Pierres",
        "ru": "Камни",
        "tr": "Taşlar",
        "ua": "Камені",
    },
    "Minutes": {
        "en": "Minutes",
        "cn": "分钟",
        "tw": "分鐘",
        "jp": "分",
        "ko": "분",
        "de": "Minuten",
        "es": "Minutos",
        "fr": "Minutes",
        "ru": "Минуты",
        "tr": "Dakika",
        "ua": "Хвилини",
    },
    "Seconds": {
        "en": "Seconds",
        "cn": "秒",
        "tw": "秒",
        "jp": "秒",
        "ko": "초",
        "de": "Sekunden",
        "es": "Segundos",
        "fr": "Secondes",
        "ru": "Секунды",
        "tr": "Saniye",
        "ua": "Секунди",
    },
    "cancel": {
        "en": "Cancel",
        "cn": "取消",
        "tw": "取消",
        "jp": "キャンセル",
        "ko": "취소",
        "de": "Abbrechen",
        "es": "Cancelar",
        "fr": "Annuler",
        "ru": "Отмена",
        "tr": "İptal",
        "ua": "Скасувати",
    },

    # Game Page - Right Sidebar
    "Items": {
        "en": "Items",
        "cn": "道具",
        "tw": "道具",
        "jp": "アイテム",
        "ko": "아이템",
        "de": "Objekte",
        "es": "Objetos",
        "fr": "Objets",
        "ru": "Предметы",
        "tr": "Öğeler",
        "ua": "Предмети",
    },
    "Territory": {
        "en": "Territory",
        "cn": "领地",
        "tw": "領地",
        "jp": "地",
        "ko": "집",
        "de": "Gebiet",
        "es": "Territorio",
        "fr": "Territoire",
        "ru": "Территория",
        "tr": "Bölge",
        "ua": "Територія",
    },
    "Advice": {
        "en": "Advice",
        "cn": "建议",
        "tw": "建議",
        "jp": "アドバイス",
        "ko": "조언",
        "de": "Ratschlag",
        "es": "Consejo",
        "fr": "Conseil",
        "ru": "Совет",
        "tr": "Tavsiye",
        "ua": "Порада",
    },
    "Graph": {
        "en": "Graph",
        "cn": "图表",
        "tw": "圖表",
        "jp": "グラフ",
        "ko": "그래프",
        "de": "Diagramm",
        "es": "Gráfico",
        "fr": "Graphique",
        "ru": "График",
        "tr": "Grafik",
        "ua": "Графік",
    },
    "Policy": {
        "en": "Policy",
        "cn": "策略",
        "tw": "策略",
        "jp": "ポリシー",
        "ko": "정책",
        "de": "Strategie",
        "es": "Política",
        "fr": "Politique",
        "ru": "Политика",
        "tr": "Politika",
        "ua": "Політика",
    },
    "Win Rate": {
        "en": "Win Rate",
        "cn": "胜率",
        "tw": "勝率",
        "jp": "勝率",
        "ko": "승률",
        "de": "Gewinnrate",
        "es": "Tasa de victoria",
        "fr": "Taux de victoire",
        "ru": "Процент побед",
        "tr": "Kazanma Oranı",
        "ua": "Відсоток перемог",
    },
    "Score Lead": {
        "en": "Score Lead",
        "cn": "领先目数",
        "tw": "領先目數",
        "jp": "目数リード",
        "ko": "점수 우위",
        "de": "Punktevorsprung",
        "es": "Ventaja de puntos",
        "fr": "Avance de points",
        "ru": "Преимущество в очках",
        "tr": "Puan Farkı",
        "ua": "Перевага в очках",
    },
    "Coordinates": {
        "en": "Coordinates",
        "cn": "坐标",
        "tw": "座標",
        "jp": "座標",
        "ko": "좌표",
        "de": "Koordinaten",
        "es": "Coordenadas",
        "fr": "Coordonnées",
        "ru": "Координаты",
        "tr": "Koordinatlar",
        "ua": "Координати",
    },
    "Move Numbers": {
        "en": "Move Numbers",
        "cn": "手数",
        "tw": "手數",
        "jp": "手数",
        "ko": "수순",
        "de": "Zugnummern",
        "es": "Números de movimiento",
        "fr": "Numéros de coups",
        "ru": "Номера ходов",
        "tr": "Hamle Numaraları",
        "ua": "Номери ходів",
    },
    "PASS": {
        "en": "PASS",
        "cn": "弃权",
        "tw": "棄權",
        "jp": "パス",
        "ko": "패스",
        "de": "PASSEN",
        "es": "PASAR",
        "fr": "PASSER",
        "ru": "ПАС",
        "tr": "PAS",
        "ua": "ПАС",
    },
    "RESIGN": {
        "en": "RESIGN",
        "cn": "认输",
        "tw": "認輸",
        "jp": "投了",
        "ko": "기권",
        "de": "AUFGEBEN",
        "es": "RENDIRSE",
        "fr": "ABANDONNER",
        "ru": "СДАТЬСЯ",
        "tr": "ADAN",
        "ua": "ЗДАТИСЯ",
    },
    "Undo (Smart)": {
        "en": "Undo (Smart)",
        "cn": "悔棋（智能）",
        "tw": "悔棋（智能）",
        "jp": "待った（スマート）",
        "ko": "무르기 (스마트)",
        "de": "Rückgängig (Smart)",
        "es": "Deshacer (Inteligente)",
        "fr": "Annuler (Intelligent)",
        "ru": "Отменить (Умный)",
        "tr": "Geri Al (Akıllı)",
        "ua": "Скасувати (Розумний)",
    },
    "Previous Mistake": {
        "en": "Previous Mistake",
        "cn": "上一个错误",
        "tw": "上一個錯誤",
        "jp": "前の悪手",
        "ko": "이전 실수",
        "de": "Vorheriger Fehler",
        "es": "Error anterior",
        "fr": "Erreur précédente",
        "ru": "Предыдущая ошибка",
        "tr": "Önceki Hata",
        "ua": "Попередня помилка",
    },
    "Next Mistake": {
        "en": "Next Mistake",
        "cn": "下一个错误",
        "tw": "下一個錯誤",
        "jp": "次の悪手",
        "ko": "다음 실수",
        "de": "Nächster Fehler",
        "es": "Siguiente error",
        "fr": "Erreur suivante",
        "ru": "Следующая ошибка",
        "tr": "Sonraki Hata",
        "ua": "Наступна помилка",
    },
    "Rotate Board": {
        "en": "Rotate Board",
        "cn": "旋转棋盘",
        "tw": "旋轉棋盤",
        "jp": "盤面を回転",
        "ko": "바둑판 회전",
        "de": "Brett drehen",
        "es": "Rotar tablero",
        "fr": "Tourner le plateau",
        "ru": "Повернуть доску",
        "tr": "Tahtayı Döndür",
        "ua": "Повернути дошку",
    },
    "AI Move": {
        "en": "AI Move",
        "cn": "AI落子",
        "tw": "AI落子",
        "jp": "AIの手",
        "ko": "AI 착수",
        "de": "KI-Zug",
        "es": "Movimiento de IA",
        "fr": "Coup de l'IA",
        "ru": "Ход ИИ",
        "tr": "Yapay Zeka Hamlesi",
        "ua": "Хід ШІ",
    },
    "exit": {
        "en": "Exit",
        "cn": "退出",
        "tw": "退出",
        "jp": "終了",
        "ko": "나가기",
        "de": "Beenden",
        "es": "Salir",
        "fr": "Quitter",
        "ru": "Выход",
        "tr": "Çıkış",
        "ua": "Вихід",
    },
    "Rules": {
        "en": "Rules",
        "cn": "规则",
        "tw": "規則",
        "jp": "ルール",
        "ko": "규칙",
        "de": "Regeln",
        "es": "Reglas",
        "fr": "Règles",
        "ru": "Правила",
        "tr": "Kurallar",
        "ua": "Правила",
    },
    "Komi": {
        "en": "Komi",
        "cn": "贴目",
        "tw": "貼目",
        "jp": "コミ",
        "ko": "덤",
        "de": "Komi",
        "es": "Komi",
        "fr": "Komi",
        "ru": "Коми",
        "tr": "Komi",
        "ua": "Комі",
    },
    "items_disabled_rated": {
        "en": "Items disabled during Rated Game",
        "cn": "升降级对局中道具已禁用",
        "tw": "升降級對局中道具已禁用",
        "jp": "レート戦中はアイテム無効",
        "ko": "레이팅 대국 중 아이템 비활성화",
        "de": "Objekte während Ranglistenspielen deaktiviert",
        "es": "Objetos deshabilitados durante partida clasificatoria",
        "fr": "Objets désactivés pendant une partie classée",
        "ru": "Предметы отключены во время рейтинговой игры",
        "tr": "Dereceli oyunda öğeler devre dışı",
        "ua": "Предмети вимкнені під час рейтингової гри",
    },
    "rated_mode_active": {
        "en": "Rated Mode: Progressing",
        "cn": "升降级模式：进行中",
        "tw": "升降級模式：進行中",
        "jp": "レートモード：進行中",
        "ko": "레이팅 모드: 진행 중",
        "de": "Ranglisten-Modus: Aktiv",
        "es": "Modo clasificatorio: En progreso",
        "fr": "Mode classé: En cours",
        "ru": "Рейтинговый режим: В процессе",
        "tr": "Dereceli Mod: Devam Ediyor",
        "ua": "Рейтинговий режим: Триває",
    },
    "rated_mode_desc": {
        "en": "Net wins tracked for rank update",
        "cn": "净胜局数将用于段位更新",
        "tw": "淨勝局數將用於段位更新",
        "jp": "ランク更新のため勝敗を記録中",
        "ko": "등급 업데이트를 위한 순승 추적 중",
        "de": "Netto-Siege werden für Rang-Update verfolgt",
        "es": "Victorias netas registradas para actualizar rango",
        "fr": "Victoires nettes suivies pour mise à jour du rang",
        "ru": "Чистые победы отслеживаются для обновления ранга",
        "tr": "Derece güncellemesi için net galibiyetler takip ediliyor",
        "ua": "Чисті перемоги відстежуються для оновлення рангу",
    },

    # Player Card - Timer labels
    "timer:main": {
        "en": "MAIN",
        "cn": "主时",
        "tw": "主時",
        "jp": "持時",
        "ko": "기본",
        "de": "HAUPT",
        "es": "PRINC",
        "fr": "PRINC",
        "ru": "ОСН",
        "tr": "ANA",
        "ua": "ОСН",
    },
    "timer:byo": {
        "en": "BYO",
        "cn": "读秒",
        "tw": "讀秒",
        "jp": "秒読",
        "ko": "초읽기",
        "de": "BYO",
        "es": "BYO",
        "fr": "BYO",
        "ru": "БЁ",
        "tr": "BYO",
        "ua": "БЙО",
    },
    "timer:periods": {
        "en": "PRD",
        "cn": "次数",
        "tw": "次數",
        "jp": "回数",
        "ko": "횟수",
        "de": "PER",
        "es": "PER",
        "fr": "PER",
        "ru": "ПЕР",
        "tr": "PER",
        "ua": "ПЕР",
    },
    "Captures": {
        "en": "Captures",
        "cn": "提子",
        "tw": "提子",
        "jp": "アゲハマ",
        "ko": "따낸 돌",
        "de": "Gefangene",
        "es": "Capturas",
        "fr": "Captures",
        "ru": "Захваты",
        "tr": "Esirler",
        "ua": "Захоплення",
    },

    # Game dialogs
    "leave_game_title": {
        "en": "Leave Game?",
        "cn": "离开对局？",
        "tw": "離開對局？",
        "jp": "ゲームを離れますか？",
        "ko": "대국을 떠나시겠습니까?",
        "de": "Spiel verlassen?",
        "es": "¿Abandonar partida?",
        "fr": "Quitter la partie ?",
        "ru": "Покинуть игру?",
        "tr": "Oyundan Çık?",
        "ua": "Покинути гру?",
    },
    "leave_game_warning": {
        "en": "The game is still in progress. Leaving will resign the game. Are you sure?",
        "cn": "对局仍在进行中。离开将自动认输。确定吗？",
        "tw": "對局仍在進行中。離開將自動認輸。確定嗎？",
        "jp": "ゲームはまだ進行中です。離れると投了となります。よろしいですか？",
        "ko": "대국이 진행 중입니다. 나가면 기권 처리됩니다. 확실합니까?",
        "de": "Das Spiel läuft noch. Verlassen bedeutet Aufgabe. Sind Sie sicher?",
        "es": "La partida está en curso. Salir significará rendirse. ¿Estás seguro?",
        "fr": "La partie est en cours. Quitter équivaudra à abandonner. Êtes-vous sûr ?",
        "ru": "Игра еще продолжается. Выход означает сдачу. Вы уверены?",
        "tr": "Oyun hala devam ediyor. Ayrılmak terk etmek anlamına gelir. Emin misiniz?",
        "ua": "Гра ще триває. Вихід означає здачу. Ви впевнені?",
    },
    "resign_and_exit": {
        "en": "Resign & Exit",
        "cn": "认输并退出",
        "tw": "認輸並退出",
        "jp": "投了して終了",
        "ko": "기권 후 나가기",
        "de": "Aufgeben & Beenden",
        "es": "Rendirse y salir",
        "fr": "Abandonner et quitter",
        "ru": "Сдаться и выйти",
        "tr": "Terk Et ve Çık",
        "ua": "Здатися і вийти",
    },
    "continue_game": {
        "en": "Continue Game",
        "cn": "继续对局",
        "tw": "繼續對局",
        "jp": "続ける",
        "ko": "계속하기",
        "de": "Spiel fortsetzen",
        "es": "Continuar partida",
        "fr": "Continuer la partie",
        "ru": "Продолжить игру",
        "tr": "Oyuna Devam Et",
        "ua": "Продовжити гру",
    },
    "resign_game_title": {
        "en": "Resign Game?",
        "cn": "认输？",
        "tw": "認輸？",
        "jp": "投了しますか？",
        "ko": "기권하시겠습니까?",
        "de": "Aufgeben?",
        "es": "¿Rendirse?",
        "fr": "Abandonner ?",
        "ru": "Сдаться?",
        "tr": "Oyunu Terk Et?",
        "ua": "Здатися?",
    },
    "resign_confirm_text": {
        "en": "Are you sure you want to resign?",
        "cn": "确定要认输吗？",
        "tw": "確定要認輸嗎？",
        "jp": "本当に投了しますか？",
        "ko": "정말 기권하시겠습니까?",
        "de": "Sind Sie sicher, dass Sie aufgeben möchten?",
        "es": "¿Estás seguro de que quieres rendirte?",
        "fr": "Êtes-vous sûr de vouloir abandonner ?",
        "ru": "Вы уверены, что хотите сдаться?",
        "tr": "Terk etmek istediğinizden emin misiniz?",
        "ua": "Ви впевнені, що хочете здатися?",
    },
    "play_vs_ai": {
        "en": "Play vs AI",
        "cn": "AI对弈",
        "tw": "AI對弈",
        "jp": "AI対戦",
        "ko": "AI 대국",
        "de": "Gegen KI spielen",
        "es": "Jugar vs IA",
        "fr": "Jouer contre l'IA",
        "ru": "Играть против ИИ",
        "tr": "Yapay Zekaya Karşı Oyna",
        "ua": "Грати проти ШІ",
    },

    # HvH Lobby
    "lobby:title": {
        "en": "Multiplayer Lobby",
        "cn": "多人游戏大厅",
        "tw": "多人遊戲大廳",
        "jp": "マルチプレイヤーロビー",
        "ko": "멀티플레이어 로비",
        "de": "Mehrspieler-Lobby",
        "es": "Sala multijugador",
        "fr": "Salon multijoueur",
        "ru": "Многопользовательское лобби",
        "tr": "Çok Oyunculu Lobi",
        "ua": "Багатокористувацьке лобі",
    },
    "lobby:subtitle": {
        "en": "Play against other humans or watch live games.",
        "cn": "与其他玩家对弈或观看直播对局。",
        "tw": "與其他玩家對弈或觀看直播對局。",
        "jp": "他のプレイヤーと対戦したり、ライブゲームを観戦したりできます。",
        "ko": "다른 플레이어와 대국하거나 실시간 경기를 관전하세요.",
        "de": "Spielen Sie gegen andere Menschen oder schauen Sie Live-Spiele.",
        "es": "Juega contra otros humanos o mira partidas en vivo.",
        "fr": "Jouez contre d'autres humains ou regardez des parties en direct.",
        "ru": "Играйте против других людей или смотрите игры в прямом эфире.",
        "tr": "Diğer insanlara karşı oynayın veya canlı oyunları izleyin.",
        "ua": "Грайте проти інших людей або дивіться ігри наживо.",
    },
    "lobby:quick_match_rated": {
        "en": "Quick Match (Rated)",
        "cn": "快速匹配（排位）",
        "tw": "快速匹配（排位）",
        "jp": "クイックマッチ（レート戦）",
        "ko": "빠른 매칭 (레이팅)",
        "de": "Schnelles Spiel (Rangliste)",
        "es": "Partida rápida (Clasificatoria)",
        "fr": "Match rapide (Classé)",
        "ru": "Быстрый матч (Рейтинговый)",
        "tr": "Hızlı Eşleşme (Dereceli)",
        "ua": "Швидкий матч (Рейтинговий)",
    },
    "lobby:custom_game": {
        "en": "Custom Game",
        "cn": "自定义对局",
        "tw": "自定義對局",
        "jp": "カスタムゲーム",
        "ko": "사용자 정의 대국",
        "de": "Benutzerdefiniertes Spiel",
        "es": "Partida personalizada",
        "fr": "Partie personnalisée",
        "ru": "Пользовательская игра",
        "tr": "Özel Oyun",
        "ua": "Користувацька гра",
    },
    "lobby:online_players": {
        "en": "Online Players",
        "cn": "在线玩家",
        "tw": "在線玩家",
        "jp": "オンラインプレイヤー",
        "ko": "온라인 플레이어",
        "de": "Online-Spieler",
        "es": "Jugadores en línea",
        "fr": "Joueurs en ligne",
        "ru": "Онлайн игроки",
        "tr": "Çevrimiçi Oyuncular",
        "ua": "Онлайн гравці",
    },
    "lobby:active_games": {
        "en": "Active Games",
        "cn": "进行中的对局",
        "tw": "進行中的對局",
        "jp": "進行中のゲーム",
        "ko": "진행 중인 대국",
        "de": "Aktive Spiele",
        "es": "Partidas activas",
        "fr": "Parties actives",
        "ru": "Активные игры",
        "tr": "Aktif Oyunlar",
        "ua": "Активні ігри",
    },
    "lobby:no_active_games": {
        "en": "No active games at the moment.",
        "cn": "当前没有进行中的对局。",
        "tw": "當前沒有進行中的對局。",
        "jp": "現在、進行中のゲームはありません。",
        "ko": "현재 진행 중인 대국이 없습니다.",
        "de": "Momentan keine aktiven Spiele.",
        "es": "No hay partidas activas en este momento.",
        "fr": "Aucune partie active pour le moment.",
        "ru": "В данный момент нет активных игр.",
        "tr": "Şu anda aktif oyun yok.",
        "ua": "На даний момент немає активних ігор.",
    },
    "lobby:active_games_desc": {
        "en": "Games will appear here once matchmaking is functional.",
        "cn": "匹配功能启用后，对局将显示在这里。",
        "tw": "匹配功能啟用後，對局將顯示在這裡。",
        "jp": "マッチメイキングが機能すると、ゲームがここに表示されます。",
        "ko": "매칭 기능이 활성화되면 대국이 여기에 표시됩니다.",
        "de": "Spiele werden hier angezeigt, sobald das Matchmaking funktioniert.",
        "es": "Las partidas aparecerán aquí cuando el emparejamiento esté funcionando.",
        "fr": "Les parties apparaîtront ici une fois le matchmaking fonctionnel.",
        "ru": "Игры появятся здесь, когда заработает поиск соперников.",
        "tr": "Eşleştirme çalıştığında oyunlar burada görünecektir.",
        "ua": "Ігри з'являться тут, коли запрацює пошук суперників.",
    },
    "lobby:finding_opponent": {
        "en": "Finding Opponent...",
        "cn": "正在寻找对手...",
        "tw": "正在尋找對手...",
        "jp": "対戦相手を探しています...",
        "ko": "상대를 찾는 중...",
        "de": "Gegner wird gesucht...",
        "es": "Buscando oponente...",
        "fr": "Recherche d'un adversaire...",
        "ru": "Поиск соперника...",
        "tr": "Rakip Aranıyor...",
        "ua": "Пошук суперника...",
    },
    "lobby:matching_desc": {
        "en": "Looking for a suitable match for you.",
        "cn": "正在为您寻找合适的对手。",
        "tw": "正在為您尋找合適的對手。",
        "jp": "あなたに適した対戦相手を探しています。",
        "ko": "적합한 상대를 찾고 있습니다.",
        "de": "Suche nach einem passenden Gegner für Sie.",
        "es": "Buscando un oponente adecuado para ti.",
        "fr": "Recherche d'un adversaire adapté pour vous.",
        "ru": "Ищем подходящего соперника для вас.",
        "tr": "Sizin için uygun bir eşleşme aranıyor.",
        "ua": "Шукаємо відповідного суперника для вас.",
    },
    "lobby:invite": {
        "en": "Invite",
        "cn": "邀请",
        "tw": "邀請",
        "jp": "招待",
        "ko": "초대",
        "de": "Einladen",
        "es": "Invitar",
        "fr": "Inviter",
        "ru": "Пригласить",
        "tr": "Davet Et",
        "ua": "Запросити",
    },
    "lobby:watch": {
        "en": "Watch",
        "cn": "观战",
        "tw": "觀戰",
        "jp": "観戦",
        "ko": "관전",
        "de": "Zuschauen",
        "es": "Ver",
        "fr": "Regarder",
        "ru": "Смотреть",
        "tr": "İzle",
        "ua": "Дивитись",
    },
    "lobby:you": {
        "en": "You",
        "cn": "你",
        "tw": "你",
        "jp": "あなた",
        "ko": "당신",
        "de": "Sie",
        "es": "Tú",
        "fr": "Vous",
        "ru": "Вы",
        "tr": "Siz",
        "ua": "Ви",
    },
    "lobby:no_players": {
        "en": "No other players online.",
        "cn": "没有其他在线玩家。",
        "tw": "沒有其他在線玩家。",
        "jp": "他にオンラインのプレイヤーはいません。",
        "ko": "다른 온라인 플레이어가 없습니다.",
        "de": "Keine anderen Spieler online.",
        "es": "No hay otros jugadores en línea.",
        "fr": "Aucun autre joueur en ligne.",
        "ru": "Нет других игроков онлайн.",
        "tr": "Başka çevrimiçi oyuncu yok.",
        "ua": "Немає інших гравців онлайн.",
    },
    "lobby:no_rank": {
        "en": "No Rank",
        "cn": "无段位",
        "tw": "無段位",
        "jp": "ランクなし",
        "ko": "등급 없음",
        "de": "Kein Rang",
        "es": "Sin rango",
        "fr": "Sans rang",
        "ru": "Без ранга",
        "tr": "Derece Yok",
        "ua": "Без рангу",
    },
    "lobby:invitation_title": {
        "en": "Game Invitation",
        "cn": "对局邀请",
        "tw": "對局邀請",
        "jp": "ゲームへの招待",
        "ko": "대국 초대",
        "de": "Spieleinladung",
        "es": "Invitación de partida",
        "fr": "Invitation à une partie",
        "ru": "Приглашение на игру",
        "tr": "Oyun Daveti",
        "ua": "Запрошення на гру",
    },
    "lobby:invitation_text": {
        "en": "{{name}} invited you to a game.",
        "cn": "{{name}} 邀请你进行对局。",
        "tw": "{{name}} 邀請你進行對局。",
        "jp": "{{name}}さんがゲームに招待しました。",
        "ko": "{{name}}님이 대국에 초대했습니다.",
        "de": "{{name}} hat Sie zu einem Spiel eingeladen.",
        "es": "{{name}} te ha invitado a una partida.",
        "fr": "{{name}} vous a invité à une partie.",
        "ru": "{{name}} пригласил вас на игру.",
        "tr": "{{name}} sizi bir oyuna davet etti.",
        "ua": "{{name}} запросив вас на гру.",
    },
    "lobby:accept": {
        "en": "Accept",
        "cn": "接受",
        "tw": "接受",
        "jp": "承諾",
        "ko": "수락",
        "de": "Annehmen",
        "es": "Aceptar",
        "fr": "Accepter",
        "ru": "Принять",
        "tr": "Kabul Et",
        "ua": "Прийняти",
    },
    "lobby:decline": {
        "en": "Decline",
        "cn": "拒绝",
        "tw": "拒絕",
        "jp": "辞退",
        "ko": "거절",
        "de": "Ablehnen",
        "es": "Rechazar",
        "fr": "Refuser",
        "ru": "Отклонить",
        "tr": "Reddet",
        "ua": "Відхилити",
    },
    "Spectators": {
        "en": "Spectators",
        "cn": "观众",
        "tw": "觀眾",
        "jp": "観戦者",
        "ko": "관전자",
        "de": "Zuschauer",
        "es": "Espectadores",
        "fr": "Spectateurs",
        "ru": "Зрители",
        "tr": "İzleyiciler",
        "ua": "Глядачі",
    },
    "Moves": {
        "en": "Moves",
        "cn": "手数",
        "tw": "手數",
        "jp": "手数",
        "ko": "수",
        "de": "Züge",
        "es": "Movimientos",
        "fr": "Coups",
        "ru": "Ходы",
        "tr": "Hamleler",
        "ua": "Ходи",
    },

    # Friends Panel
    "Friends & Following": {
        "en": "Friends & Following",
        "cn": "好友与关注",
        "tw": "好友與關注",
        "jp": "フレンドとフォロー",
        "ko": "친구 및 팔로잉",
        "de": "Freunde & Gefolgt",
        "es": "Amigos y seguidos",
        "fr": "Amis et abonnements",
        "ru": "Друзья и подписки",
        "tr": "Arkadaşlar ve Takip",
        "ua": "Друзі та підписки",
    },
    "no_friends_desc": {
        "en": "You are not following anyone yet.",
        "cn": "你还没有关注任何人。",
        "tw": "你還沒有關注任何人。",
        "jp": "まだ誰もフォローしていません。",
        "ko": "아직 아무도 팔로우하지 않았습니다.",
        "de": "Sie folgen noch niemandem.",
        "es": "Aún no sigues a nadie.",
        "fr": "Vous ne suivez personne pour l'instant.",
        "ru": "Вы еще ни на кого не подписаны.",
        "tr": "Henüz kimseyi takip etmiyorsunuz.",
        "ua": "Ви ще нікого не відстежуєте.",
    },

    # Game Room specific
    "Game Over": {
        "en": "Game Over",
        "cn": "对局结束",
        "tw": "對局結束",
        "jp": "ゲーム終了",
        "ko": "게임 종료",
        "de": "Spiel beendet",
        "es": "Partida terminada",
        "fr": "Partie terminée",
        "ru": "Игра окончена",
        "tr": "Oyun Bitti",
        "ua": "Гра закінчена",
    },
    "game_room:your_turn": {
        "en": "Your Turn",
        "cn": "轮到你了",
        "tw": "輪到你了",
        "jp": "あなたの番です",
        "ko": "당신의 차례입니다",
        "de": "Sie sind dran",
        "es": "Tu turno",
        "fr": "Votre tour",
        "ru": "Ваш ход",
        "tr": "Sizin Sıranız",
        "ua": "Ваш хід",
    },
    "game_room:opponents_turn": {
        "en": "Opponent's Turn",
        "cn": "对手回合",
        "tw": "對手回合",
        "jp": "相手の番",
        "ko": "상대방의 차례",
        "de": "Gegner ist dran",
        "es": "Turno del oponente",
        "fr": "Tour de l'adversaire",
        "ru": "Ход соперника",
        "tr": "Rakibin Sırası",
        "ua": "Хід суперника",
    },
    "game_room:spectating": {
        "en": "Spectating",
        "cn": "观战中",
        "tw": "觀戰中",
        "jp": "観戦中",
        "ko": "관전 중",
        "de": "Zuschauen",
        "es": "Observando",
        "fr": "Observation",
        "ru": "Наблюдение",
        "tr": "İzleniyor",
        "ua": "Спостереження",
    },
    "game_room:leave": {
        "en": "Leave Game",
        "cn": "离开对局",
        "tw": "離開對局",
        "jp": "ゲームを離れる",
        "ko": "대국 나가기",
        "de": "Spiel verlassen",
        "es": "Salir de la partida",
        "fr": "Quitter la partie",
        "ru": "Покинуть игру",
        "tr": "Oyundan Ayrıl",
        "ua": "Покинути гру",
    },
    "game_room:leave_forfeit": {
        "en": "Leave & Forfeit",
        "cn": "离开并弃权",
        "tw": "離開並棄權",
        "jp": "離れて没収試合",
        "ko": "나가고 기권하기",
        "de": "Verlassen & Aufgeben",
        "es": "Salir y abandonar",
        "fr": "Quitter et abandonner",
        "ru": "Покинуть и сдаться",
        "tr": "Ayrıl ve Pes Et",
        "ua": "Покинути і здатися",
    },
    "game_room:forfeit_warning": {
        "en": "Leaving will forfeit the game. Are you sure?",
        "cn": "离开将导致弃权。确定吗？",
        "tw": "離開將導致棄權。確定嗎？",
        "jp": "離れると没収試合になります。よろしいですか？",
        "ko": "나가면 기권 처리됩니다. 확실합니까?",
        "de": "Verlassen führt zur Aufgabe. Sind Sie sicher?",
        "es": "Salir significará abandonar la partida. ¿Estás seguro?",
        "fr": "Quitter entraînera un forfait. Êtes-vous sûr ?",
        "ru": "Выход приведет к поражению. Вы уверены?",
        "tr": "Ayrılmak oyunu kaybetmenize neden olacak. Emin misiniz?",
        "ua": "Вихід призведе до програшу. Ви впевнені?",
    },
    "game_room:back_to_lobby": {
        "en": "Back to Lobby",
        "cn": "返回大厅",
        "tw": "返回大廳",
        "jp": "ロビーに戻る",
        "ko": "로비로 돌아가기",
        "de": "Zurück zur Lobby",
        "es": "Volver al lobby",
        "fr": "Retour au salon",
        "ru": "Вернуться в лобби",
        "tr": "Lobiye Dön",
        "ua": "Повернутися до лобі",
    },
    "game_end:resign_win": {
        "en": "You won! Opponent resigned.",
        "cn": "你赢了！对手认输。",
        "tw": "你贏了！對手認輸。",
        "jp": "あなたの勝ち！相手が投了しました。",
        "ko": "승리했습니다! 상대가 기권했습니다.",
        "de": "Sie haben gewonnen! Gegner hat aufgegeben.",
        "es": "¡Ganaste! El oponente se rindió.",
        "fr": "Vous avez gagné ! L'adversaire a abandonné.",
        "ru": "Вы выиграли! Соперник сдался.",
        "tr": "Kazandınız! Rakip terk etti.",
        "ua": "Ви виграли! Суперник здався.",
    },
    "game_end:resign_loss": {
        "en": "You resigned.",
        "cn": "你认输了。",
        "tw": "你認輸了。",
        "jp": "あなたが投了しました。",
        "ko": "기권했습니다.",
        "de": "Sie haben aufgegeben.",
        "es": "Te rendiste.",
        "fr": "Vous avez abandonné.",
        "ru": "Вы сдались.",
        "tr": "Terk ettiniz.",
        "ua": "Ви здалися.",
    },
    "game_end:timeout_win": {
        "en": "You won on time!",
        "cn": "你因超时获胜！",
        "tw": "你因超時獲勝！",
        "jp": "時間切れであなたの勝ち！",
        "ko": "시간 초과로 승리했습니다!",
        "de": "Sie haben durch Zeitüberschreitung gewonnen!",
        "es": "¡Ganaste por tiempo!",
        "fr": "Vous avez gagné au temps !",
        "ru": "Вы выиграли по времени!",
        "tr": "Süre aşımı ile kazandınız!",
        "ua": "Ви виграли за часом!",
    },
    "game_end:timeout_loss": {
        "en": "You lost on time.",
        "cn": "你因超时落败。",
        "tw": "你因超時落敗。",
        "jp": "時間切れで負け。",
        "ko": "시간 초과로 패배했습니다.",
        "de": "Sie haben durch Zeitüberschreitung verloren.",
        "es": "Perdiste por tiempo.",
        "fr": "Vous avez perdu au temps.",
        "ru": "Вы проиграли по времени.",
        "tr": "Süre aşımı ile kaybettiniz.",
        "ua": "Ви програли за часом.",
    },
    "game_end:forfeit_win": {
        "en": "You won! Opponent forfeited.",
        "cn": "你赢了！对手弃权。",
        "tw": "你贏了！對手棄權。",
        "jp": "あなたの勝ち！相手が棄権しました。",
        "ko": "승리했습니다! 상대가 기권했습니다.",
        "de": "Sie haben gewonnen! Gegner hat aufgegeben.",
        "es": "¡Ganaste! El oponente abandonó.",
        "fr": "Vous avez gagné ! L'adversaire a abandonné.",
        "ru": "Вы выиграли! Соперник отказался.",
        "tr": "Kazandınız! Rakip pes etti.",
        "ua": "Ви виграли! Суперник відмовився.",
    },
    "game_end:forfeit_loss": {
        "en": "You forfeited the game.",
        "cn": "你弃权了。",
        "tw": "你棄權了。",
        "jp": "あなたが棄権しました。",
        "ko": "기권했습니다.",
        "de": "Sie haben aufgegeben.",
        "es": "Abandonaste la partida.",
        "fr": "Vous avez abandonné la partie.",
        "ru": "Вы отказались от игры.",
        "tr": "Oyunu kaybettiniz.",
        "ua": "Ви відмовилися від гри.",
    },

    # Misc
    "Loading Board...": {
        "en": "Loading Board...",
        "cn": "正在加载棋盘...",
        "tw": "正在載入棋盤...",
        "jp": "盤面を読み込み中...",
        "ko": "바둑판 로딩 중...",
        "de": "Brett wird geladen...",
        "es": "Cargando tablero...",
        "fr": "Chargement du plateau...",
        "ru": "Загрузка доски...",
        "tr": "Tahta Yükleniyor...",
        "ua": "Завантаження дошки...",
    },
    "Analysis": {
        "en": "Analysis",
        "cn": "分析",
        "tw": "分析",
        "jp": "分析",
        "ko": "분석",
        "de": "Analyse",
        "es": "Análisis",
        "fr": "Analyse",
        "ru": "Анализ",
        "tr": "Analiz",
        "ua": "Аналіз",
    },
    "Library": {
        "en": "Library",
        "cn": "棋谱库",
        "tw": "棋譜庫",
        "jp": "ライブラリ",
        "ko": "라이브러리",
        "de": "Bibliothek",
        "es": "Biblioteca",
        "fr": "Bibliothèque",
        "ru": "Библиотека",
        "tr": "Kütüphane",
        "ua": "Бібліотека",
    },

    # Game Results
    "game:white_wins_resign": {
        "en": "White wins by resignation",
        "cn": "白棋中盘胜",
        "tw": "白棋中盤勝",
        "jp": "白の中押し勝ち",
        "ko": "백 불계승",
        "de": "Weiß gewinnt durch Aufgabe",
        "es": "Blanco gana por abandono",
        "fr": "Blanc gagne par abandon",
        "ru": "Белые выиграли сдачей",
        "tr": "Beyaz istifa ile kazandı",
        "ua": "Білі виграли здачею",
    },
    "game:black_wins_resign": {
        "en": "Black wins by resignation",
        "cn": "黑棋中盘胜",
        "tw": "黑棋中盤勝",
        "jp": "黒の中押し勝ち",
        "ko": "흑 불계승",
        "de": "Schwarz gewinnt durch Aufgabe",
        "es": "Negro gana por abandono",
        "fr": "Noir gagne par abandon",
        "ru": "Чёрные выиграли сдачей",
        "tr": "Siyah istifa ile kazandı",
        "ua": "Чорні виграли здачею",
    },
    "game:white_wins_timeout": {
        "en": "White wins by timeout",
        "cn": "白棋超时胜",
        "tw": "白棋超時勝",
        "jp": "白の時間切れ勝ち",
        "ko": "백 시간승",
        "de": "Weiß gewinnt durch Zeitüberschreitung",
        "es": "Blanco gana por tiempo",
        "fr": "Blanc gagne au temps",
        "ru": "Белые выиграли по времени",
        "tr": "Beyaz zaman aşımı ile kazandı",
        "ua": "Білі виграли по часу",
    },
    "game:black_wins_timeout": {
        "en": "Black wins by timeout",
        "cn": "黑棋超时胜",
        "tw": "黑棋超時勝",
        "jp": "黒の時間切れ勝ち",
        "ko": "흑 시간승",
        "de": "Schwarz gewinnt durch Zeitüberschreitung",
        "es": "Negro gana por tiempo",
        "fr": "Noir gagne au temps",
        "ru": "Чёрные выиграли по времени",
        "tr": "Siyah zaman aşımı ile kazandı",
        "ua": "Чорні виграли по часу",
    },
    "game:white_wins_points": {
        "en": "White wins by {n} points",
        "cn": "白棋胜{n}目",
        "tw": "白棋勝{n}目",
        "jp": "白{n}目勝ち",
        "ko": "백 {n}집 승",
        "de": "Weiß gewinnt mit {n} Punkten",
        "es": "Blanco gana por {n} puntos",
        "fr": "Blanc gagne de {n} points",
        "ru": "Белые выиграли {n} очков",
        "tr": "Beyaz {n} puan ile kazandı",
        "ua": "Білі виграли {n} очок",
    },
    "game:black_wins_points": {
        "en": "Black wins by {n} points",
        "cn": "黑棋胜{n}目",
        "tw": "黑棋勝{n}目",
        "jp": "黒{n}目勝ち",
        "ko": "흑 {n}집 승",
        "de": "Schwarz gewinnt mit {n} Punkten",
        "es": "Negro gana por {n} puntos",
        "fr": "Noir gagne de {n} points",
        "ru": "Чёрные выиграли {n} очков",
        "tr": "Siyah {n} puan ile kazandı",
        "ua": "Чорні виграли {n} очок",
    },

    # ==========================================
    # Tsumego Module
    # ==========================================
    "Tsumego": {
        "en": "Tsumego",
        "cn": "死活题",
        "tw": "死活題",
        "jp": "詰碁",
        "ko": "사활",
        "de": "Tsumego",
        "es": "Tsumego",
        "fr": "Tsumego",
        "ru": "Цумего",
        "tr": "Tsumego",
        "ua": "Цумего",
    },
    "tsumego:selectLevel": {
        "en": "Select Difficulty Level",
        "cn": "选择难度级别",
        "tw": "選擇難度級別",
        "jp": "難易度を選択",
        "ko": "난이도 선택",
        "de": "Schwierigkeitsstufe wählen",
        "es": "Seleccionar nivel de dificultad",
        "fr": "Sélectionner le niveau de difficulté",
        "ru": "Выберите уровень сложности",
        "tr": "Zorluk seviyesi seçin",
        "ua": "Оберіть рівень складності",
    },
    "tsumego:practiceProblems": {
        "en": "Practice life and death problems to improve your reading",
        "cn": "练习死活题以提高计算能力",
        "tw": "練習死活題以提高計算能力",
        "jp": "詰碁を練習して読みを鍛えましょう",
        "ko": "사활 문제를 풀어 수읽기를 향상시키세요",
        "de": "Üben Sie Leben-und-Tod-Probleme, um Ihre Lesefähigkeit zu verbessern",
        "es": "Practica problemas de vida y muerte para mejorar tu lectura",
        "fr": "Pratiquez les problèmes de vie et mort pour améliorer votre lecture",
        "ru": "Решайте задачи на жизнь и смерть, чтобы улучшить чтение",
        "tr": "Okuma becerilerinizi geliştirmek için yaşam ve ölüm problemleri çözün",
        "ua": "Вирішуйте задачі на життя і смерть для покращення читання",
    },
    "tsumego:selectCategory": {
        "en": "Select Category",
        "cn": "选择题型",
        "tw": "選擇題型",
        "jp": "カテゴリを選択",
        "ko": "유형 선택",
        "de": "Kategorie wählen",
        "es": "Seleccionar categoría",
        "fr": "Sélectionner la catégorie",
        "ru": "Выберите категорию",
        "tr": "Kategori seçin",
        "ua": "Оберіть категорію",
    },
    "tsumego:categoryDesc": {
        "en": "Choose the type of problems you want to practice",
        "cn": "选择你想要练习的题型",
        "tw": "選擇你想要練習的題型",
        "jp": "練習したい問題の種類を選択",
        "ko": "연습하고 싶은 문제 유형을 선택하세요",
        "de": "Wählen Sie die Art der Probleme, die Sie üben möchten",
        "es": "Elige el tipo de problemas que quieres practicar",
        "fr": "Choisissez le type de problèmes que vous voulez pratiquer",
        "ru": "Выберите тип задач для практики",
        "tr": "Pratik yapmak istediğiniz problem türünü seçin",
        "ua": "Оберіть тип задач для практики",
    },
    "tsumego:problems": {
        "en": "problems",
        "cn": "题",
        "tw": "題",
        "jp": "問",
        "ko": "문제",
        "de": "Aufgaben",
        "es": "problemas",
        "fr": "problèmes",
        "ru": "задач",
        "tr": "problem",
        "ua": "задач",
    },
    "tsumego:solveProblems": {
        "en": "Click a problem to start practicing",
        "cn": "点击题目开始练习",
        "tw": "點擊題目開始練習",
        "jp": "問題をクリックして練習を開始",
        "ko": "문제를 클릭하여 연습 시작",
        "de": "Klicken Sie auf ein Problem, um zu üben",
        "es": "Haz clic en un problema para empezar a practicar",
        "fr": "Cliquez sur un problème pour commencer à pratiquer",
        "ru": "Нажмите на задачу, чтобы начать практику",
        "tr": "Pratik yapmak için bir probleme tıklayın",
        "ua": "Натисніть на задачу, щоб почати практику",
    },
    "tsumego:life-death": {
        "en": "Life & Death",
        "cn": "死活",
        "tw": "死活",
        "jp": "死活",
        "ko": "사활",
        "de": "Leben & Tod",
        "es": "Vida y Muerte",
        "fr": "Vie et Mort",
        "ru": "Жизнь и смерть",
        "tr": "Yaşam ve Ölüm",
        "ua": "Життя і смерть",
    },
    "tsumego:tesuji": {
        "en": "Tesuji",
        "cn": "手筋",
        "tw": "手筋",
        "jp": "手筋",
        "ko": "수근",
        "de": "Tesuji",
        "es": "Tesuji",
        "fr": "Tesuji",
        "ru": "Тэсудзи",
        "tr": "Tesuji",
        "ua": "Тесуджі",
    },
    "tsumego:endgame": {
        "en": "Endgame",
        "cn": "官子",
        "tw": "官子",
        "jp": "ヨセ",
        "ko": "끝내기",
        "de": "Endspiel",
        "es": "Final",
        "fr": "Fin de partie",
        "ru": "Эндшпиль",
        "tr": "Son oyun",
        "ua": "Ендшпіль",
    },
    "tsumego:problem_n": {
        "en": "Problem {n}",
        "cn": "第{n}题",
        "tw": "第{n}題",
        "jp": "問題{n}",
        "ko": "문제 {n}",
        "de": "Aufgabe {n}",
        "es": "Problema {n}",
        "fr": "Problème {n}",
        "ru": "Задача {n}",
        "tr": "Problem {n}",
        "ua": "Задача {n}",
    },
    "tsumego:solved": {
        "en": "Solved!",
        "cn": "正确！",
        "tw": "正確！",
        "jp": "正解！",
        "ko": "정답!",
        "de": "Gelöst!",
        "es": "¡Resuelto!",
        "fr": "Résolu !",
        "ru": "Решено!",
        "tr": "Çözüldü!",
        "ua": "Вирішено!",
    },
    "tsumego:incorrect": {
        "en": "Incorrect",
        "cn": "错误",
        "tw": "錯誤",
        "jp": "不正解",
        "ko": "오답",
        "de": "Falsch",
        "es": "Incorrecto",
        "fr": "Incorrect",
        "ru": "Неверно",
        "tr": "Yanlış",
        "ua": "Невірно",
    },
    "tsumego:blackToPlay": {
        "en": "Black to play",
        "cn": "黑先",
        "tw": "黑先",
        "jp": "黒番",
        "ko": "흑 선",
        "de": "Schwarz am Zug",
        "es": "Negro juega",
        "fr": "Noir joue",
        "ru": "Ход чёрных",
        "tr": "Siyah oynuyor",
        "ua": "Хід чорних",
    },
    "tsumego:whiteToPlay": {
        "en": "White to play",
        "cn": "白先",
        "tw": "白先",
        "jp": "白番",
        "ko": "백 선",
        "de": "Weiß am Zug",
        "es": "Blanco juega",
        "fr": "Blanc joue",
        "ru": "Ход белых",
        "tr": "Beyaz oynuyor",
        "ua": "Хід білих",
    },
    "tsumego:attempts": {
        "en": "Attempts",
        "cn": "尝试次数",
        "tw": "嘗試次數",
        "jp": "試行回数",
        "ko": "시도 횟수",
        "de": "Versuche",
        "es": "Intentos",
        "fr": "Tentatives",
        "ru": "Попытки",
        "tr": "Denemeler",
        "ua": "Спроби",
    },
    "tsumego:showHint": {
        "en": "Show Hint",
        "cn": "显示提示",
        "tw": "顯示提示",
        "jp": "ヒントを表示",
        "ko": "힌트 보기",
        "de": "Hinweis zeigen",
        "es": "Mostrar pista",
        "fr": "Afficher l'indice",
        "ru": "Показать подсказку",
        "tr": "İpucu Göster",
        "ua": "Показати підказку",
    },
    "tsumego:hideHint": {
        "en": "Hide Hint",
        "cn": "隐藏提示",
        "tw": "隱藏提示",
        "jp": "ヒントを隠す",
        "ko": "힌트 숨기기",
        "de": "Hinweis verbergen",
        "es": "Ocultar pista",
        "fr": "Masquer l'indice",
        "ru": "Скрыть подсказку",
        "tr": "İpucu Gizle",
        "ua": "Приховати підказку",
    },
    "tsumego:undo": {
        "en": "Undo",
        "cn": "撤销",
        "tw": "撤銷",
        "jp": "戻る",
        "ko": "되돌리기",
        "de": "Rückgängig",
        "es": "Deshacer",
        "fr": "Annuler",
        "ru": "Отменить",
        "tr": "Geri Al",
        "ua": "Скасувати",
    },
    "tsumego:reset": {
        "en": "Reset",
        "cn": "重置",
        "tw": "重置",
        "jp": "リセット",
        "ko": "초기화",
        "de": "Zurücksetzen",
        "es": "Reiniciar",
        "fr": "Réinitialiser",
        "ru": "Сбросить",
        "tr": "Sıfırla",
        "ua": "Скинути",
    },
    "tsumego:previousProblem": {
        "en": "Previous",
        "cn": "上一题",
        "tw": "上一題",
        "jp": "前の問題",
        "ko": "이전",
        "de": "Vorherige",
        "es": "Anterior",
        "fr": "Précédent",
        "ru": "Предыдущая",
        "tr": "Önceki",
        "ua": "Попередня",
    },
    "tsumego:nextProblem": {
        "en": "Next",
        "cn": "下一题",
        "tw": "下一題",
        "jp": "次の問題",
        "ko": "다음",
        "de": "Nächste",
        "es": "Siguiente",
        "fr": "Suivant",
        "ru": "Следующая",
        "tr": "Sonraki",
        "ua": "Наступна",
    },
    "tsumego:errorLoading": {
        "en": "Error Loading Problem",
        "cn": "加载题目失败",
        "tw": "載入題目失敗",
        "jp": "問題の読み込みエラー",
        "ko": "문제 로딩 오류",
        "de": "Fehler beim Laden",
        "es": "Error al cargar",
        "fr": "Erreur de chargement",
        "ru": "Ошибка загрузки",
        "tr": "Yükleme Hatası",
        "ua": "Помилка завантаження",
    },
    # Tsumego Unit Grouping (2026-01-23)
    "tsumego:selectUnit": {
        "en": "Select Unit",
        "cn": "选择单元",
        "tw": "選擇單元",
        "jp": "ユニットを選択",
        "ko": "단원 선택",
        "de": "Einheit wählen",
        "es": "Seleccionar unidad",
        "fr": "Sélectionner l'unité",
        "ru": "Выберите раздел",
        "tr": "Ünite seçin",
        "ua": "Оберіть розділ",
    },
    "tsumego:unitDesc": {
        "en": "Total {total} problems in {units} units",
        "cn": "共 {total} 题，分为 {units} 个单元",
        "tw": "共 {total} 題，分為 {units} 個單元",
        "jp": "全{total}問、{units}ユニットに分類",
        "ko": "총 {total}문제, {units}개 단원",
        "de": "Insgesamt {total} Aufgaben in {units} Einheiten",
        "es": "Total de {total} problemas en {units} unidades",
        "fr": "Total de {total} problèmes en {units} unités",
        "ru": "Всего {total} задач в {units} разделах",
        "tr": "Toplam {total} problem, {units} ünite",
        "ua": "Всього {total} задач у {units} розділах",
    },
    "tsumego:unit": {
        "en": "Unit",
        "cn": "单元",
        "tw": "單元",
        "jp": "ユニット",
        "ko": "단원",
        "de": "Einheit",
        "es": "Unidad",
        "fr": "Unité",
        "ru": "Раздел",
        "tr": "Ünite",
        "ua": "Розділ",
    },
    "tsumego:problemRange": {
        "en": "Problems {start}-{end}",
        "cn": "第 {start}-{end} 题",
        "tw": "第 {start}-{end} 題",
        "jp": "問題 {start}-{end}",
        "ko": "문제 {start}-{end}",
        "de": "Aufgaben {start}-{end}",
        "es": "Problemas {start}-{end}",
        "fr": "Problèmes {start}-{end}",
        "ru": "Задачи {start}-{end}",
        "tr": "Problem {start}-{end}",
        "ua": "Задачі {start}-{end}",
    },
    "tsumego:tryMode": {
        "en": "Try Mode",
        "cn": "试下",
        "tw": "試下",
        "jp": "試しモード",
        "ko": "시험 모드",
        "de": "Probier-Modus",
        "es": "Modo de prueba",
        "fr": "Mode essai",
        "ru": "Режим пробы",
        "tr": "Deneme Modu",
        "ua": "Режим проби",
    },
    "tsumego:tryModeDesc": {
        "en": "Free exploration without judgment",
        "cn": "自由探索，不判断对错",
        "tw": "自由探索，不判斷對錯",
        "jp": "判定なしの自由探索",
        "ko": "판정 없이 자유 탐색",
        "de": "Freies Erkunden ohne Bewertung",
        "es": "Exploración libre sin juicio",
        "fr": "Exploration libre sans jugement",
        "ru": "Свободное исследование без оценки",
        "tr": "Değerlendirme olmadan serbest keşif",
        "ua": "Вільне дослідження без оцінки",
    },
    # Auth / Login Modal
    "auth:login_title": {
        "en": "Login to Galaxy Go",
        "cn": "登录 Galaxy Go",
        "tw": "登入 Galaxy Go",
        "jp": "Galaxy Goにログイン",
        "ko": "Galaxy Go 로그인",
        "de": "Bei Galaxy Go anmelden",
        "es": "Iniciar sesión en Galaxy Go",
        "fr": "Connexion à Galaxy Go",
        "ru": "Войти в Galaxy Go",
        "tr": "Galaxy Go'ya Giriş Yap",
        "ua": "Увійти до Galaxy Go",
    },
    "auth:login_title_katrain": {
        "en": "Login to KaTrain",
        "cn": "登录 KaTrain",
        "tw": "登入 KaTrain",
        "jp": "KaTrainにログイン",
        "ko": "KaTrain 로그인",
        "de": "Bei KaTrain anmelden",
        "es": "Iniciar sesión en KaTrain",
        "fr": "Connexion à KaTrain",
        "ru": "Войти в KaTrain",
        "tr": "KaTrain'e Giriş Yap",
        "ua": "Увійти до KaTrain",
    },
    "auth:register_title": {
        "en": "Create Account",
        "cn": "创建账号",
        "tw": "建立帳號",
        "jp": "アカウント作成",
        "ko": "계정 생성",
        "de": "Konto erstellen",
        "es": "Crear cuenta",
        "fr": "Créer un compte",
        "ru": "Создать аккаунт",
        "tr": "Hesap Oluştur",
        "ua": "Створити акаунт",
    },
    "auth:username": {
        "en": "Username",
        "cn": "用户名",
        "tw": "用戶名",
        "jp": "ユーザー名",
        "ko": "사용자 이름",
        "de": "Benutzername",
        "es": "Nombre de usuario",
        "fr": "Nom d'utilisateur",
        "ru": "Имя пользователя",
        "tr": "Kullanıcı Adı",
        "ua": "Ім'я користувача",
    },
    "auth:password": {
        "en": "Password",
        "cn": "密码",
        "tw": "密碼",
        "jp": "パスワード",
        "ko": "비밀번호",
        "de": "Passwort",
        "es": "Contraseña",
        "fr": "Mot de passe",
        "ru": "Пароль",
        "tr": "Şifre",
        "ua": "Пароль",
    },
    "auth:confirm_password": {
        "en": "Confirm Password",
        "cn": "确认密码",
        "tw": "確認密碼",
        "jp": "パスワード再入力",
        "ko": "비밀번호 확인",
        "de": "Passwort bestätigen",
        "es": "Confirmar contraseña",
        "fr": "Confirmer le mot de passe",
        "ru": "Подтвердите пароль",
        "tr": "Şifreyi Onayla",
        "ua": "Підтвердіть пароль",
    },
    "auth:login_btn": {
        "en": "Login",
        "cn": "登录",
        "tw": "登入",
        "jp": "ログイン",
        "ko": "로그인",
        "de": "Anmelden",
        "es": "Iniciar sesión",
        "fr": "Connexion",
        "ru": "Войти",
        "tr": "Giriş Yap",
        "ua": "Увійти",
    },
    "auth:register_btn": {
        "en": "Register",
        "cn": "注册",
        "tw": "註冊",
        "jp": "登録",
        "ko": "가입",
        "de": "Registrieren",
        "es": "Registrarse",
        "fr": "S'inscrire",
        "ru": "Зарегистрироваться",
        "tr": "Kayıt Ol",
        "ua": "Зареєструватися",
    },
    "auth:cancel_btn": {
        "en": "Cancel",
        "cn": "取消",
        "tw": "取消",
        "jp": "キャンセル",
        "ko": "취소",
        "de": "Abbrechen",
        "es": "Cancelar",
        "fr": "Annuler",
        "ru": "Отмена",
        "tr": "İptal",
        "ua": "Скасувати",
    },
    "auth:logging_in": {
        "en": "Logging in...",
        "cn": "正在登录...",
        "tw": "正在登入...",
        "jp": "ログイン中...",
        "ko": "로그인 중...",
        "de": "Wird angemeldet...",
        "es": "Iniciando sesión...",
        "fr": "Connexion en cours...",
        "ru": "Вход...",
        "tr": "Giriş yapılıyor...",
        "ua": "Вхід...",
    },
    "auth:registering": {
        "en": "Registering...",
        "cn": "正在注册...",
        "tw": "正在註冊...",
        "jp": "登録中...",
        "ko": "가입 중...",
        "de": "Wird registriert...",
        "es": "Registrando...",
        "fr": "Inscription en cours...",
        "ru": "Регистрация...",
        "tr": "Kayıt olunuyor...",
        "ua": "Реєстрація...",
    },
    "auth:switch_to_register": {
        "en": "Don't have an account? Register",
        "cn": "没有账号？注册",
        "tw": "沒有帳號？註冊",
        "jp": "アカウントをお持ちでないですか？登録",
        "ko": "계정이 없으신가요? 가입",
        "de": "Noch kein Konto? Registrieren",
        "es": "¿No tienes una cuenta? Regístrate",
        "fr": "Pas de compte ? S'inscrire",
        "ru": "Нет аккаунта? Зарегистрироваться",
        "tr": "Hesabınız yok mu? Kayıt Ol",
        "ua": "Немає акаунту? Зареєструватися",
    },
    "auth:switch_to_login": {
        "en": "Already have an account? Login",
        "cn": "已有账号？登录",
        "tw": "已有帳號？登入",
        "jp": "すでにアカウントをお持ちですか？ログイン",
        "ko": "이미 계정이 있으신가요? 로그인",
        "de": "Bereits ein Konto? Anmelden",
        "es": "¿Ya tienes una cuenta? Inicia sesión",
        "fr": "Déjà un compte ? Connexion",
        "ru": "Уже есть аккаунт? Войти",
        "tr": "Zaten bir hesabınız mı var? Giriş Yap",
        "ua": "Вже є акаунт? Увійти",
    },
    "auth:err_fill_all": {
        "en": "Please fill in all fields",
        "cn": "请填写所有字段",
        "tw": "請填寫所有欄位",
        "jp": "すべての項目を入力してください",
        "ko": "모든 필드를 채워주세요",
        "de": "Bitte füllen Sie alle Felder aus",
        "es": "Por favor, completa todos los campos",
        "fr": "Veuillez remplir tous les champs",
        "ru": "Пожалуйста, заполните все поля",
        "tr": "Lütfen tüm alanları doldurun",
        "ua": "Будь ласка, заповніть усі поля",
    },
    "auth:err_pass_mismatch": {
        "en": "Passwords do not match",
        "cn": "密码不匹配",
        "tw": "密碼不匹配",
        "jp": "パスワードが一致しません",
        "ko": "비밀번호가 일치하지 않습니다",
        "de": "Passwörter stimmen nicht überein",
        "es": "Las contraseñas no coinciden",
        "fr": "Les mots de passe ne correspondent pas",
        "ru": "Пароли не совпадают",
        "tr": "Şifreler eşleşmiyor",
        "ua": "Паролі не збігаються",
    },
    "auth:success_register": {
        "en": "Registration successful! Logging in...",
        "cn": "注册成功！正在登录...",
        "tw": "註冊成功！正在登入...",
        "jp": "登録に成功しました！ログインしています...",
        "ko": "가입 성공! 로그인 중...",
        "de": "Registrierung erfolgreich! Anmeldung erfolgt...",
        "es": "¡Registro exitoso! Iniciando sesión...",
        "fr": "Inscription réussie ! Connexion...",
        "ru": "Регистрация прошла успешно! Вход...",
        "tr": "Kayıt başarılı! Giriş yapılıyor...",
        "ua": "Реєстрація успішна! Вхід...",
    },
    "auth:err_failed": {
        "en": "Operation failed",
        "cn": "操作失败",
        "tw": "操作失敗",
        "jp": "操作に失敗しました",
        "ko": "작업 실패",
        "de": "Vorgang fehlgeschlagen",
        "es": "Operación fallida",
        "fr": "L'opération a échoué",
        "ru": "Операция не удалась",
        "tr": "İşlem başarısız oldu",
        "ua": "Операція не вдалася",
    },

    # Trend Chart axis labels
    "live:black_winrate": {
        "en": "Black Winrate",
        "cn": "黑棋胜率",
        "tw": "黑棋勝率",
        "jp": "黒勝率",
        "ko": "흑 승률",
        "de": "Schwarz Gewinnrate",
        "es": "Porcentaje Negro",
        "fr": "Taux Noir",
        "ru": "Процент черных",
        "tr": "Siyah Kazanma",
        "ua": "Відсоток чорних",
    },
    "live:black_lead": {
        "en": "Black Lead",
        "cn": "黑棋领先",
        "tw": "黑棋領先",
        "jp": "黒リード",
        "ko": "흑 우세",
        "de": "Schwarz Vorsprung",
        "es": "Ventaja Negro",
        "fr": "Avance Noir",
        "ru": "Преим. черных",
        "tr": "Siyah Avantaj",
        "ua": "Перевага чорних",
    },

    # Live module feature buttons
    "live:try": {
        "en": "TRY",
        "cn": "试下",
        "tw": "試下",
        "jp": "試着",
        "ko": "시도",
        "de": "TEST",
        "es": "PROBAR",
        "fr": "ESSAI",
        "ru": "ПРОБА",
        "tr": "DENE",
        "ua": "СПРОБА",
    },
    "live:territory": {
        "en": "TERRITORY",
        "cn": "领地",
        "tw": "領地",
        "jp": "地",
        "ko": "집",
        "de": "GEBIET",
        "es": "TERRITORIO",
        "fr": "TERRITOIRE",
        "ru": "ТЕРРИТОРИЯ",
        "tr": "BÖLGE",
        "ua": "ТЕРИТОРІЯ",
    },
    "live:move_numbers": {
        "en": "Numbers",
        "cn": "手数",
        "tw": "手數",
        "jp": "手番",
        "ko": "수순",
        "de": "Nummern",
        "es": "Números",
        "fr": "Numéros",
        "ru": "Номера",
        "tr": "Sayılar",
        "ua": "Номери",
    },
    "live:points_unit": {
        "en": "pts",
        "cn": "目",
        "tw": "目",
        "jp": "目",
        "ko": "집",
        "de": "Pkt",
        "es": "pts",
        "fr": "pts",
        "ru": "очк",
        "tr": "puan",
        "ua": "очк",
    },
    "Undo": {
        "en": "Undo",
        "cn": "悔棋",
        "tw": "悔棋",
        "jp": "待った",
        "ko": "무르기",
        "de": "Rückgängig",
        "es": "Deshacer",
        "fr": "Annuler",
        "ru": "Отменить",
        "tr": "Geri Al",
        "ua": "Скасувати",
    },
    "Advice": {
        "en": "Advice",
        "cn": "建议",
        "tw": "建議",
        "jp": "提案",
        "ko": "조언",
        "de": "Rat",
        "es": "Consejo",
        "fr": "Conseil",
        "ru": "Совет",
        "tr": "Tavsiye",
        "ua": "Порада",
    },
    "live:show_advice": {
        "en": "Show Advice",
        "cn": "显示建议",
        "tw": "顯示建議",
        "jp": "提案を表示",
        "ko": "조언 표시",
        "de": "Rat anzeigen",
        "es": "Mostrar consejo",
        "fr": "Afficher conseil",
        "ru": "Показать совет",
        "tr": "Tavsiye Göster",
        "ua": "Показати пораду",
    },
    "live:moves": {
        "en": "moves",
        "cn": "手",
        "tw": "手",
        "jp": "手",
        "ko": "수",
        "de": "Züge",
        "es": "movs",
        "fr": "coups",
        "ru": "ходов",
        "tr": "hamle",
        "ua": "ходів",
    },
    "live:status_live": {
        "en": "LIVE",
        "cn": "直播中",
        "tw": "直播中",
        "jp": "ライブ",
        "ko": "라이브",
        "de": "LIVE",
        "es": "EN VIVO",
        "fr": "EN DIRECT",
        "ru": "LIVE",
        "tr": "CANLI",
        "ua": "НАЖИВО",
    },
    "live:status_finished": {
        "en": "Finished",
        "cn": "已结束",
        "tw": "已結束",
        "jp": "終了",
        "ko": "종료",
        "de": "Beendet",
        "es": "Finalizado",
        "fr": "Terminé",
        "ru": "Завершено",
        "tr": "Bitti",
        "ua": "Завершено",
    },
    "live:hide_advice": {
        "en": "Hide Advice",
        "cn": "隐藏建议",
        "tw": "隱藏建議",
        "jp": "提案を非表示",
        "ko": "조언 숨김",
        "de": "Rat ausblenden",
        "es": "Ocultar consejo",
        "fr": "Masquer conseil",
        "ru": "Скрыть совет",
        "tr": "Tavsiye Gizle",
        "ua": "Сховати пораду",
    },

    # Player rank and type
    "No Rank": {
        "en": "No Rank",
        "cn": "无级别",
        "tw": "無級別",
        "jp": "ランクなし",
        "ko": "급수 없음",
        "de": "Kein Rang",
        "es": "Sin rango",
        "fr": "Sans rang",
        "ru": "Без ранга",
        "tr": "Rütbesiz",
        "ua": "Без рангу",
    },
    "ai:human_like": {
        "en": "Human-like",
        "cn": "拟人",
        "tw": "擬人",
        "jp": "人間風",
        "ko": "인간형",
        "de": "Menschenähnlich",
        "es": "Humanoide",
        "fr": "Humain",
        "ru": "Человечный",
        "tr": "İnsan benzeri",
        "ua": "Людиноподібний",
    },
    "ai:historical_pro": {
        "en": "Historical Pro",
        "cn": "历史棋风",
        "tw": "歷史棋風",
        "jp": "過去のプロ風",
        "ko": "역사적 프로",
        "de": "Historischer Pro",
        "es": "Pro Histórico",
        "fr": "Pro Historique",
        "ru": "Исторический про",
        "tr": "Tarihi Pro",
        "ua": "Історичний про",
    },
    "ai:score_loss": {
        "en": "Score Loss",
        "cn": "目数损失",
        "tw": "目數損失",
        "jp": "目数損失",
        "ko": "점수 손실",
        "de": "Punktverlust",
        "es": "Pérdida de Puntos",
        "fr": "Perte de Points",
        "ru": "Потеря очков",
        "tr": "Puan Kaybı",
        "ua": "Втрата очок",
    },
    "ai:simple_ownership": {
        "en": "Simple Ownership",
        "cn": "简单地域",
        "tw": "簡單地域",
        "jp": "シンプル地",
        "ko": "단순 영역",
        "de": "Einfaches Gebiet",
        "es": "Territorio Simple",
        "fr": "Territoire Simple",
        "ru": "Простая территория",
        "tr": "Basit Bölge",
        "ua": "Проста територія",
    },
    "ai:calibrated_rank": {
        "en": "Calibrated Rank",
        "cn": "校准级别",
        "tw": "校準級別",
        "jp": "校正済みランク",
        "ko": "보정 급수",
        "de": "Kalibrierter Rang",
        "es": "Rango Calibrado",
        "fr": "Rang Calibré",
        "ru": "Калиброванный ранг",
        "tr": "Kalibre Derece",
        "ua": "Калібрований ранг",
    },
    "ai:weighted": {
        "en": "Weighted",
        "cn": "加权",
        "tw": "加權",
        "jp": "加重",
        "ko": "가중",
        "de": "Gewichtet",
        "es": "Ponderado",
        "fr": "Pondéré",
        "ru": "Взвешенный",
        "tr": "Ağırlıklı",
        "ua": "Зважений",
    },
    "ai:policy_pick": {
        "en": "Policy Pick",
        "cn": "策略选择",
        "tw": "策略選擇",
        "jp": "ポリシー選択",
        "ko": "정책 선택",
        "de": "Strategie-Auswahl",
        "es": "Selección de Política",
        "fr": "Choix de Politique",
        "ru": "Выбор политики",
        "tr": "Politika Seçimi",
        "ua": "Вибір політики",
    },
    "ai:local": {
        "en": "Local",
        "cn": "局部",
        "tw": "局部",
        "jp": "ローカル",
        "ko": "지역",
        "de": "Lokal",
        "es": "Local",
        "fr": "Local",
        "ru": "Локальный",
        "tr": "Yerel",
        "ua": "Локальний",
    },
    "ai:tenuki": {
        "en": "Tenuki",
        "cn": "脱先",
        "tw": "脫先",
        "jp": "手抜き",
        "ko": "탈선",
        "de": "Tenuki",
        "es": "Tenuki",
        "fr": "Tenuki",
        "ru": "Тенуки",
        "tr": "Tenuki",
        "ua": "Тенукі",
    },
    "ai:influence": {
        "en": "Influence",
        "cn": "外势",
        "tw": "外勢",
        "jp": "厚み",
        "ko": "세력",
        "de": "Einfluss",
        "es": "Influencia",
        "fr": "Influence",
        "ru": "Влияние",
        "tr": "Etki",
        "ua": "Вплив",
    },
    "ai:territory": {
        "en": "Territory",
        "cn": "实地",
        "tw": "實地",
        "jp": "地",
        "ko": "집",
        "de": "Gebiet",
        "es": "Territorio",
        "fr": "Territoire",
        "ru": "Территория",
        "tr": "Bölge",
        "ua": "Територія",
    },
    "ai:policy": {
        "en": "Policy",
        "cn": "策略",
        "tw": "策略",
        "jp": "ポリシー",
        "ko": "정책",
        "de": "Strategie",
        "es": "Política",
        "fr": "Politique",
        "ru": "Политика",
        "tr": "Politika",
        "ua": "Політика",
    },
    "ai:jigo": {
        "en": "Jigo",
        "cn": "和棋",
        "tw": "和棋",
        "jp": "持碁",
        "ko": "빅",
        "de": "Jigo",
        "es": "Jigo",
        "fr": "Jigo",
        "ru": "Дзиго",
        "tr": "Jigo",
        "ua": "Дзіго",
    },
    "ai:antimirror": {
        "en": "Anti-mirror",
        "cn": "反模仿",
        "tw": "反模仿",
        "jp": "マネ碁対策",
        "ko": "반모방",
        "de": "Anti-Spiegel",
        "es": "Anti-espejo",
        "fr": "Anti-miroir",
        "ru": "Анти-зеркало",
        "tr": "Anti-ayna",
        "ua": "Анти-дзеркало",
    },
}


def update_po_file(lang_code: str, translations: dict):
    """Update a single .po file with translations."""
    po_path = I18N_DIR / lang_code / "LC_MESSAGES" / "katrain.po"

    if not po_path.exists():
        print(f"  Warning: {po_path} does not exist, skipping...")
        return 0

    po = polib.pofile(str(po_path))
    updated_count = 0

    # Build a lookup of existing entries by msgid
    existing_entries = {entry.msgid: entry for entry in po}

    for msgid, lang_translations in translations.items():
        if lang_code not in lang_translations:
            continue

        msgstr = lang_translations[lang_code]

        if msgid in existing_entries:
            entry = existing_entries[msgid]
            # Update if different or empty
            if entry.msgstr != msgstr:
                entry.msgstr = msgstr
                updated_count += 1
            
            # CRITICAL: Clear TODO comments so i18n.py doesn't overwrite these with English
            if entry.comment and "TODO" in entry.comment:
                # Remove "TODO - " or "TODO" from the start/middle
                new_comment = entry.comment.replace("TODO - ", "").replace("TODO", "").strip()
                if entry.comment != new_comment:
                    entry.comment = new_comment
                    updated_count += 1
        else:
            # Add new entry
            new_entry = polib.POEntry(msgid=msgid, msgstr=msgstr)
            po.append(new_entry)
            updated_count += 1

    if updated_count > 0:
        po.save(str(po_path))

    return updated_count


def main():
    """Main function to update all language files."""
    print("=" * 60)
    print("KaTrain Galaxy UI Batch Translation Script")
    print("=" * 60)

    languages = ["en", "cn", "tw", "jp", "ko", "de", "es", "fr", "ru", "tr", "ua"]

    total_updates = 0

    for lang in languages:
        print(f"\nProcessing {lang}...")
        count = update_po_file(lang, GALAXY_TRANSLATIONS)
        print(f"  Updated {count} entries")
        total_updates += count

    print(f"\n{'=' * 60}")
    print(f"Total entries updated across all languages: {total_updates}")
    print("=" * 60)
    print("\nNext steps:")
    print("1. Run 'python i18n.py' to compile .mo files")
    print("2. Run 'cd katrain/web/ui && npm run build' to rebuild frontend")
    print("3. Restart the server to see changes")


if __name__ == "__main__":
    main()
