#!/usr/bin/env python3
"""
Batch translation script for KaTrain Galaxy UI.
Updates all language files with proper translations for Galaxy UI keys.

Usage:
    python scripts/batch_translate_galaxy.py

Requirements:
    pip install polib
"""

import os
import polib
from pathlib import Path

# Project paths
PROJECT_ROOT = Path(__file__).parent.parent
I18N_DIR = PROJECT_ROOT / "katrain" / "i18n" / "locales"

# All Galaxy UI translation keys with translations for each language
# Format: {msgid: {lang_code: msgstr}}
GALAXY_TRANSLATIONS = {
    # Dashboard
    "dashboard:welcome": {
        "en": "Welcome to Galaxy Go",
        "cn": "欢迎来到 Galaxy Go",
        "tw": "歡迎來到 Galaxy Go",
        "jp": "Galaxy Goへようこそ",
        "ko": "Galaxy Go에 오신 것을 환영합니다",
        "de": "Willkommen bei Galaxy Go",
        "es": "Bienvenido a Galaxy Go",
        "fr": "Bienvenue sur Galaxy Go",
        "ru": "Добро пожаловать в Galaxy Go",
        "tr": "Galaxy Go'ya Hoş Geldiniz",
        "ua": "Ласкаво просимо до Galaxy Go",
    },
    "dashboard:tagline": {
        "en": "Your professional Go training and analysis platform.",
        "cn": "您的专业围棋训练与分析平台。",
        "tw": "您的專業圍棋訓練與分析平台。",
        "jp": "プロフェッショナルな囲碁トレーニング＆分析プラットフォーム。",
        "ko": "전문적인 바둑 훈련 및 분석 플랫폼.",
        "de": "Ihre professionelle Go-Trainings- und Analyseplattform.",
        "es": "Tu plataforma profesional de entrenamiento y análisis de Go.",
        "fr": "Votre plateforme professionnelle d'entraînement et d'analyse de Go.",
        "ru": "Ваша профессиональная платформа для обучения и анализа игры в Го.",
        "tr": "Profesyonel Go eğitim ve analiz platformunuz.",
        "ua": "Ваша професійна платформа для навчання та аналізу гри в Го.",
    },
    "dashboard:play_desc": {
        "en": "Challenge AI opponents or play against friends. Features Rated games to establish your rank.",
        "cn": "挑战AI对手或与朋友对弈。支持升降级对局以确定您的等级。",
        "tw": "挑戰AI對手或與朋友對弈。支持升降級對局以確定您的等級。",
        "jp": "AIと対戦したり、友達と対戦したりできます。レート戦で段位を確立できます。",
        "ko": "AI 상대와 대결하거나 친구와 대국하세요. 레이팅 게임으로 등급을 확립하세요.",
        "de": "Fordern Sie KI-Gegner heraus oder spielen Sie gegen Freunde. Ranglistenspiele zur Bestimmung Ihres Ranges.",
        "es": "Desafía a oponentes de IA o juega contra amigos. Partidas clasificatorias para establecer tu rango.",
        "fr": "Affrontez des adversaires IA ou jouez contre des amis. Parties classées pour établir votre rang.",
        "ru": "Играйте против ИИ или друзей. Рейтинговые игры для определения вашего ранга.",
        "tr": "Yapay zeka rakiplerine meydan okuyun veya arkadaşlarınızla oynayın. Derecenizi belirlemek için dereceli oyunlar.",
        "ua": "Грайте проти ШІ або друзів. Рейтингові ігри для визначення вашого рангу.",
    },
    "dashboard:research_desc": {
        "en": "Analyze games with AI, explore variations, and manage your SGF library.",
        "cn": "使用AI分析棋谱，探索变化，管理您的SGF棋谱库。",
        "tw": "使用AI分析棋譜，探索變化，管理您的SGF棋譜庫。",
        "jp": "AIでゲームを分析し、変化を探索し、SGFライブラリを管理します。",
        "ko": "AI로 기보를 분석하고, 변화를 탐색하고, SGF 라이브러리를 관리하세요.",
        "de": "Analysieren Sie Spiele mit KI, erkunden Sie Variationen und verwalten Sie Ihre SGF-Bibliothek.",
        "es": "Analiza partidas con IA, explora variaciones y gestiona tu biblioteca SGF.",
        "fr": "Analysez des parties avec l'IA, explorez les variations et gérez votre bibliothèque SGF.",
        "ru": "Анализируйте игры с помощью ИИ, исследуйте варианты и управляйте библиотекой SGF.",
        "tr": "Yapay zeka ile oyunları analiz edin, varyasyonları keşfedin ve SGF kütüphanenizi yönetin.",
        "ua": "Аналізуйте ігри з ШІ, досліджуйте варіанти та керуйте бібліотекою SGF.",
    },
    "dashboard:report_desc": {
        "en": "Detailed game reports and style analysis. (Coming Soon)",
        "cn": "详细的对局报告和风格分析。(即将推出)",
        "tw": "詳細的對局報告和風格分析。(即將推出)",
        "jp": "詳細なゲームレポートとスタイル分析。（近日公開）",
        "ko": "상세한 게임 리포트와 스타일 분석. (곧 출시)",
        "de": "Detaillierte Spielberichte und Stilanalyse. (Demnächst)",
        "es": "Informes detallados de partidas y análisis de estilo. (Próximamente)",
        "fr": "Rapports de parties détaillés et analyse de style. (Bientôt disponible)",
        "ru": "Подробные отчеты об играх и анализ стиля. (Скоро)",
        "tr": "Ayrıntılı oyun raporları ve stil analizi. (Yakında)",
        "ua": "Детальні звіти про ігри та аналіз стилю. (Незабаром)",
    },
    "dashboard:live_desc": {
        "en": "Watch top games and live tournaments. (Coming Soon)",
        "cn": "观看顶级对局和现场锦标赛。(即将推出)",
        "tw": "觀看頂級對局和現場錦標賽。(即將推出)",
        "jp": "トップゲームやライブトーナメントを観戦。（近日公開）",
        "ko": "최고 수준의 대국과 실시간 대회 관전. (곧 출시)",
        "de": "Top-Spiele und Live-Turniere ansehen. (Demnächst)",
        "es": "Ver partidas de alto nivel y torneos en vivo. (Próximamente)",
        "fr": "Regardez les meilleures parties et tournois en direct. (Bientôt disponible)",
        "ru": "Смотрите лучшие игры и турниры в прямом эфире. (Скоро)",
        "tr": "En iyi oyunları ve canlı turnuvaları izleyin. (Yakında)",
        "ua": "Дивіться топові ігри та турніри в прямому ефірі. (Незабаром)",
    },

    # Sidebar / Navigation
    "Settings": {
        "en": "Settings",
        "cn": "设置",
        "tw": "設定",
        "jp": "設定",
        "ko": "설정",
        "de": "Einstellungen",
        "es": "Configuración",
        "fr": "Paramètres",
        "ru": "Настройки",
        "tr": "Ayarlar",
        "ua": "Налаштування",
    },
    "Research": {
        "en": "Research",
        "cn": "研究",
        "tw": "研究",
        "jp": "研究",
        "ko": "연구",
        "de": "Forschung",
        "es": "Investigación",
        "fr": "Recherche",
        "ru": "Исследование",
        "tr": "Araştırma",
        "ua": "Дослідження",
    },
    "Live": {
        "en": "Live",
        "cn": "直播",
        "tw": "直播",
        "jp": "ライブ",
        "ko": "라이브",
        "de": "Live",
        "es": "En vivo",
        "fr": "En direct",
        "ru": "Прямой эфир",
        "tr": "Canlı",
        "ua": "Наживо",
    },
    "Login": {
        "en": "Sign In",
        "cn": "登录",
        "tw": "登入",
        "jp": "ログイン",
        "ko": "로그인",
        "de": "Anmelden",
        "es": "Iniciar sesión",
        "fr": "Connexion",
        "ru": "Войти",
        "tr": "Giriş Yap",
        "ua": "Увійти",
    },
    "Language": {
        "en": "Language",
        "cn": "语言",
        "tw": "語言",
        "jp": "言語",
        "ko": "언어",
        "de": "Sprache",
        "es": "Idioma",
        "fr": "Langue",
        "ru": "Язык",
        "tr": "Dil",
        "ua": "Мова",
    },

    # Play Menu
    "play:choose_mode": {
        "en": "Choose your game mode",
        "cn": "选择游戏模式",
        "tw": "選擇遊戲模式",
        "jp": "ゲームモードを選択",
        "ko": "게임 모드 선택",
        "de": "Wählen Sie Ihren Spielmodus",
        "es": "Elige tu modo de juego",
        "fr": "Choisissez votre mode de jeu",
        "ru": "Выберите режим игры",
        "tr": "Oyun modunuzu seçin",
        "ua": "Оберіть режим гри",
    },
    "play:vs_ai_free": {
        "en": "Play vs AI (Free)",
        "cn": "自由对弈",
        "tw": "自由對弈",
        "jp": "AI対戦（フリー）",
        "ko": "AI 대국 (자유)",
        "de": "Gegen KI spielen (Frei)",
        "es": "Jugar vs IA (Libre)",
        "fr": "Jouer contre l'IA (Libre)",
        "ru": "Играть против ИИ (Свободная)",
        "tr": "Yapay Zekaya Karşı Oyna (Serbest)",
        "ua": "Грати проти ШІ (Вільна)",
    },
    "play:vs_ai_free_desc": {
        "en": "Practice with full analysis, undo, and custom settings.",
        "cn": "练习模式，支持完整分析、悔棋和自定义设置。",
        "tw": "練習模式，支持完整分析、悔棋和自定義設定。",
        "jp": "完全な分析、待った、カスタム設定で練習できます。",
        "ko": "완전한 분석, 되돌리기, 사용자 설정으로 연습하세요.",
        "de": "Üben Sie mit vollständiger Analyse, Rückgängig und benutzerdefinierten Einstellungen.",
        "es": "Practica con análisis completo, deshacer y configuración personalizada.",
        "fr": "Entraînez-vous avec analyse complète, annulation et paramètres personnalisés.",
        "ru": "Практикуйтесь с полным анализом, отменой хода и настройками.",
        "tr": "Tam analiz, geri alma ve özel ayarlarla pratik yapın.",
        "ua": "Практикуйтесь з повним аналізом, скасуванням ходу та налаштуваннями.",
    },
    "play:rated_ai": {
        "en": "Rated Game vs AI",
        "cn": "升降级对局",
        "tw": "升降級對局",
        "jp": "レート戦 vs AI",
        "ko": "레이팅 대국 vs AI",
        "de": "Ranglistenspiel gegen KI",
        "es": "Partida clasificatoria vs IA",
        "fr": "Partie classée vs IA",
        "ru": "Рейтинговая игра против ИИ",
        "tr": "Dereceli Oyun vs Yapay Zeka",
        "ua": "Рейтингова гра проти ШІ",
    },
    "play:rated_ai_desc": {
        "en": "Play a ranked game against a human-like AI. No analysis during game.",
        "cn": "与拟人AI进行排位赛。对局中无分析功能。",
        "tw": "與擬人AI進行排位賽。對局中無分析功能。",
        "jp": "人間らしいAIとランク戦をプレイ。ゲーム中の分析はありません。",
        "ko": "인간형 AI와 랭크 대국. 대국 중 분석 없음.",
        "de": "Spielen Sie ein Ranglistenspiel gegen eine menschenähnliche KI. Keine Analyse während des Spiels.",
        "es": "Juega una partida clasificatoria contra una IA similar a humanos. Sin análisis durante la partida.",
        "fr": "Jouez une partie classée contre une IA humanoïde. Pas d'analyse pendant la partie.",
        "ru": "Играйте рейтинговую игру против человекоподобного ИИ. Без анализа во время игры.",
        "tr": "İnsan benzeri bir yapay zekaya karşı dereceli oyun oynayın. Oyun sırasında analiz yok.",
        "ua": "Грайте рейтингову гру проти людиноподібного ШІ. Без аналізу під час гри.",
    },
    "play:hvh": {
        "en": "Human vs Human",
        "cn": "人人对弈",
        "tw": "人人對弈",
        "jp": "人間対人間",
        "ko": "인간 대 인간",
        "de": "Mensch gegen Mensch",
        "es": "Humano vs Humano",
        "fr": "Humain contre Humain",
        "ru": "Человек против человека",
        "tr": "İnsan vs İnsan",
        "ua": "Людина проти людини",
    },
    "play:hvh_desc": {
        "en": "Challenge a friend or find an opponent online.",
        "cn": "挑战好友或在线匹配对手。",
        "tw": "挑戰好友或在線匹配對手。",
        "jp": "友達に挑戦するか、オンラインで対戦相手を見つけましょう。",
        "ko": "친구에게 도전하거나 온라인에서 상대를 찾으세요.",
        "de": "Fordern Sie einen Freund heraus oder finden Sie einen Gegner online.",
        "es": "Desafía a un amigo o encuentra un oponente en línea.",
        "fr": "Défiez un ami ou trouvez un adversaire en ligne.",
        "ru": "Бросьте вызов другу или найдите соперника онлайн.",
        "tr": "Bir arkadaşınıza meydan okuyun veya çevrimiçi rakip bulun.",
        "ua": "Киньте виклик другу або знайдіть суперника онлайн.",
    },

    # AI Setup Page
    "play:free_play_setup": {
        "en": "Free Play Setup",
        "cn": "自由对弈设置",
        "tw": "自由對弈設定",
        "jp": "フリープレイ設定",
        "ko": "자유 대국 설정",
        "de": "Freispiel-Einstellungen",
        "es": "Configuración de juego libre",
        "fr": "Configuration du jeu libre",
        "ru": "Настройка свободной игры",
        "tr": "Serbest Oyun Ayarları",
        "ua": "Налаштування вільної гри",
    },
    "play:rated_ai_setup": {
        "en": "Rated AI Game Setup",
        "cn": "升降级对局设置",
        "tw": "升降級對局設定",
        "jp": "レート戦設定",
        "ko": "레이팅 대국 설정",
        "de": "Ranglistenspiel-Einstellungen",
        "es": "Configuración de partida clasificatoria",
        "fr": "Configuration de partie classée",
        "ru": "Настройка рейтинговой игры",
        "tr": "Dereceli Oyun Ayarları",
        "ua": "Налаштування рейтингової гри",
    },
    "Board & Rules": {
        "en": "Board & Rules",
        "cn": "棋盘与规则",
        "tw": "棋盤與規則",
        "jp": "盤面とルール",
        "ko": "바둑판 및 규칙",
        "de": "Brett & Regeln",
        "es": "Tablero y reglas",
        "fr": "Plateau et règles",
        "ru": "Доска и правила",
        "tr": "Tahta ve Kurallar",
        "ua": "Дошка та правила",
    },
    "Opponent & Time": {
        "en": "Opponent & Time",
        "cn": "对手与时间",
        "tw": "對手與時間",
        "jp": "対戦相手と時間",
        "ko": "상대 및 시간",
        "de": "Gegner & Zeit",
        "es": "Oponente y tiempo",
        "fr": "Adversaire et temps",
        "ru": "Соперник и время",
        "tr": "Rakip ve Süre",
        "ua": "Суперник та час",
    },
    "Your Color": {
        "en": "Your Color",
        "cn": "执子颜色",
        "tw": "執子顏色",
        "jp": "あなたの色",
        "ko": "당신의 색",
        "de": "Ihre Farbe",
        "es": "Tu color",
        "fr": "Votre couleur",
        "ru": "Ваш цвет",
        "tr": "Sizin Renginiz",
        "ua": "Ваш колір",
    },
    "Black": {
        "en": "Black",
        "cn": "黑棋",
        "tw": "黑棋",
        "jp": "黒",
        "ko": "흑",
        "de": "Schwarz",
        "es": "Negro",
        "fr": "Noir",
        "ru": "Черные",
        "tr": "Siyah",
        "ua": "Чорні",
    },
    "White": {
        "en": "White",
        "cn": "白棋",
        "tw": "白棋",
        "jp": "白",
        "ko": "백",
        "de": "Weiß",
        "es": "Blanco",
        "fr": "Blanc",
        "ru": "Белые",
        "tr": "Beyaz",
        "ua": "Білі",
    },
    "First": {
        "en": "First",
        "cn": "先手",
        "tw": "先手",
        "jp": "先手",
        "ko": "선수",
        "de": "Erster",
        "es": "Primero",
        "fr": "Premier",
        "ru": "Первый",
        "tr": "İlk",
        "ua": "Перший",
    },
    "Second": {
        "en": "Second",
        "cn": "后手",
        "tw": "後手",
        "jp": "後手",
        "ko": "후수",
        "de": "Zweiter",
        "es": "Segundo",
        "fr": "Second",
        "ru": "Второй",
        "tr": "İkinci",
        "ua": "Другий",
    },
    "Enable Timer": {
        "en": "Enable Timer",
        "cn": "启用计时器",
        "tw": "啟用計時器",
        "jp": "タイマーを有効にする",
        "ko": "타이머 활성화",
        "de": "Timer aktivieren",
        "es": "Habilitar temporizador",
        "fr": "Activer le chronomètre",
        "ru": "Включить таймер",
        "tr": "Zamanlayıcıyı Etkinleştir",
        "ua": "Увімкнути таймер",
    },
    "Rank": {
        "en": "Rank",
        "cn": "段位",
        "tw": "段位",
        "jp": "段位",
        "ko": "급수",
        "de": "Rang",
        "es": "Rango",
        "fr": "Rang",
        "ru": "Ранг",
        "tr": "Derece",
        "ua": "Ранг",
    },
    "Standard": {
        "en": "Standard",
        "cn": "标准",
        "tw": "標準",
        "jp": "標準",
        "ko": "표준",
        "de": "Standard",
        "es": "Estándar",
        "fr": "Standard",
        "ru": "Стандартный",
        "tr": "Standart",
        "ua": "Стандартний",
    },
    "Stones": {
        "en": "Stones",
        "cn": "让子",
        "tw": "讓子",
        "jp": "子",
        "ko": "돌",
        "de": "Steine",
        "es": "Piedras",
        "fr": "Pierres",
        "ru": "Камни",
        "tr": "Taşlar",
        "ua": "Камені",
    },
    "Minutes": {
        "en": "Minutes",
        "cn": "分钟",
        "tw": "分鐘",
        "jp": "分",
        "ko": "분",
        "de": "Minuten",
        "es": "Minutos",
        "fr": "Minutes",
        "ru": "Минуты",
        "tr": "Dakika",
        "ua": "Хвилини",
    },
    "Seconds": {
        "en": "Seconds",
        "cn": "秒",
        "tw": "秒",
        "jp": "秒",
        "ko": "초",
        "de": "Sekunden",
        "es": "Segundos",
        "fr": "Secondes",
        "ru": "Секунды",
        "tr": "Saniye",
        "ua": "Секунди",
    },
    "cancel": {
        "en": "Cancel",
        "cn": "取消",
        "tw": "取消",
        "jp": "キャンセル",
        "ko": "취소",
        "de": "Abbrechen",
        "es": "Cancelar",
        "fr": "Annuler",
        "ru": "Отмена",
        "tr": "İptal",
        "ua": "Скасувати",
    },

    # Game Page - Right Sidebar
    "Items": {
        "en": "Items",
        "cn": "道具",
        "tw": "道具",
        "jp": "アイテム",
        "ko": "아이템",
        "de": "Objekte",
        "es": "Objetos",
        "fr": "Objets",
        "ru": "Предметы",
        "tr": "Öğeler",
        "ua": "Предмети",
    },
    "Territory": {
        "en": "Territory",
        "cn": "领地",
        "tw": "領地",
        "jp": "地",
        "ko": "집",
        "de": "Gebiet",
        "es": "Territorio",
        "fr": "Territoire",
        "ru": "Территория",
        "tr": "Bölge",
        "ua": "Територія",
    },
    "Advice": {
        "en": "Advice",
        "cn": "建议",
        "tw": "建議",
        "jp": "アドバイス",
        "ko": "조언",
        "de": "Ratschlag",
        "es": "Consejo",
        "fr": "Conseil",
        "ru": "Совет",
        "tr": "Tavsiye",
        "ua": "Порада",
    },
    "Graph": {
        "en": "Graph",
        "cn": "图表",
        "tw": "圖表",
        "jp": "グラフ",
        "ko": "그래프",
        "de": "Diagramm",
        "es": "Gráfico",
        "fr": "Graphique",
        "ru": "График",
        "tr": "Grafik",
        "ua": "Графік",
    },
    "Policy": {
        "en": "Policy",
        "cn": "策略",
        "tw": "策略",
        "jp": "ポリシー",
        "ko": "정책",
        "de": "Strategie",
        "es": "Política",
        "fr": "Politique",
        "ru": "Политика",
        "tr": "Politika",
        "ua": "Політика",
    },
    "Win Rate": {
        "en": "Win Rate",
        "cn": "胜率",
        "tw": "勝率",
        "jp": "勝率",
        "ko": "승률",
        "de": "Gewinnrate",
        "es": "Tasa de victoria",
        "fr": "Taux de victoire",
        "ru": "Процент побед",
        "tr": "Kazanma Oranı",
        "ua": "Відсоток перемог",
    },
    "Score Lead": {
        "en": "Score Lead",
        "cn": "领先目数",
        "tw": "領先目數",
        "jp": "目数リード",
        "ko": "점수 우위",
        "de": "Punktevorsprung",
        "es": "Ventaja de puntos",
        "fr": "Avance de points",
        "ru": "Преимущество в очках",
        "tr": "Puan Farkı",
        "ua": "Перевага в очках",
    },
    "Coordinates": {
        "en": "Coordinates",
        "cn": "坐标",
        "tw": "座標",
        "jp": "座標",
        "ko": "좌표",
        "de": "Koordinaten",
        "es": "Coordenadas",
        "fr": "Coordonnées",
        "ru": "Координаты",
        "tr": "Koordinatlar",
        "ua": "Координати",
    },
    "Move Numbers": {
        "en": "Move Numbers",
        "cn": "手数",
        "tw": "手數",
        "jp": "手数",
        "ko": "수순",
        "de": "Zugnummern",
        "es": "Números de movimiento",
        "fr": "Numéros de coups",
        "ru": "Номера ходов",
        "tr": "Hamle Numaraları",
        "ua": "Номери ходів",
    },
    "PASS": {
        "en": "PASS",
        "cn": "弃权",
        "tw": "棄權",
        "jp": "パス",
        "ko": "패스",
        "de": "PASSEN",
        "es": "PASAR",
        "fr": "PASSER",
        "ru": "ПАС",
        "tr": "PAS",
        "ua": "ПАС",
    },
    "RESIGN": {
        "en": "RESIGN",
        "cn": "认输",
        "tw": "認輸",
        "jp": "投了",
        "ko": "기권",
        "de": "AUFGEBEN",
        "es": "RENDIRSE",
        "fr": "ABANDONNER",
        "ru": "СДАТЬСЯ",
        "tr": "ADAN",
        "ua": "ЗДАТИСЯ",
    },
    "Undo (Smart)": {
        "en": "Undo (Smart)",
        "cn": "悔棋（智能）",
        "tw": "悔棋（智能）",
        "jp": "待った（スマート）",
        "ko": "무르기 (스마트)",
        "de": "Rückgängig (Smart)",
        "es": "Deshacer (Inteligente)",
        "fr": "Annuler (Intelligent)",
        "ru": "Отменить (Умный)",
        "tr": "Geri Al (Akıllı)",
        "ua": "Скасувати (Розумний)",
    },
    "Previous Mistake": {
        "en": "Previous Mistake",
        "cn": "上一个错误",
        "tw": "上一個錯誤",
        "jp": "前の悪手",
        "ko": "이전 실수",
        "de": "Vorheriger Fehler",
        "es": "Error anterior",
        "fr": "Erreur précédente",
        "ru": "Предыдущая ошибка",
        "tr": "Önceki Hata",
        "ua": "Попередня помилка",
    },
    "Next Mistake": {
        "en": "Next Mistake",
        "cn": "下一个错误",
        "tw": "下一個錯誤",
        "jp": "次の悪手",
        "ko": "다음 실수",
        "de": "Nächster Fehler",
        "es": "Siguiente error",
        "fr": "Erreur suivante",
        "ru": "Следующая ошибка",
        "tr": "Sonraki Hata",
        "ua": "Наступна помилка",
    },
    "Rotate Board": {
        "en": "Rotate Board",
        "cn": "旋转棋盘",
        "tw": "旋轉棋盤",
        "jp": "盤面を回転",
        "ko": "바둑판 회전",
        "de": "Brett drehen",
        "es": "Rotar tablero",
        "fr": "Tourner le plateau",
        "ru": "Повернуть доску",
        "tr": "Tahtayı Döndür",
        "ua": "Повернути дошку",
    },
    "AI Move": {
        "en": "AI Move",
        "cn": "AI落子",
        "tw": "AI落子",
        "jp": "AIの手",
        "ko": "AI 착수",
        "de": "KI-Zug",
        "es": "Movimiento de IA",
        "fr": "Coup de l'IA",
        "ru": "Ход ИИ",
        "tr": "Yapay Zeka Hamlesi",
        "ua": "Хід ШІ",
    },
    "exit": {
        "en": "Exit",
        "cn": "退出",
        "tw": "退出",
        "jp": "終了",
        "ko": "나가기",
        "de": "Beenden",
        "es": "Salir",
        "fr": "Quitter",
        "ru": "Выход",
        "tr": "Çıkış",
        "ua": "Вихід",
    },
    "Rules": {
        "en": "Rules",
        "cn": "规则",
        "tw": "規則",
        "jp": "ルール",
        "ko": "규칙",
        "de": "Regeln",
        "es": "Reglas",
        "fr": "Règles",
        "ru": "Правила",
        "tr": "Kurallar",
        "ua": "Правила",
    },
    "Komi": {
        "en": "Komi",
        "cn": "贴目",
        "tw": "貼目",
        "jp": "コミ",
        "ko": "덤",
        "de": "Komi",
        "es": "Komi",
        "fr": "Komi",
        "ru": "Коми",
        "tr": "Komi",
        "ua": "Комі",
    },
    "items_disabled_rated": {
        "en": "Items disabled during Rated Game",
        "cn": "升降级对局中道具已禁用",
        "tw": "升降級對局中道具已禁用",
        "jp": "レート戦中はアイテム無効",
        "ko": "레이팅 대국 중 아이템 비활성화",
        "de": "Objekte während Ranglistenspielen deaktiviert",
        "es": "Objetos deshabilitados durante partida clasificatoria",
        "fr": "Objets désactivés pendant une partie classée",
        "ru": "Предметы отключены во время рейтинговой игры",
        "tr": "Dereceli oyunda öğeler devre dışı",
        "ua": "Предмети вимкнені під час рейтингової гри",
    },
    "rated_mode_active": {
        "en": "Rated Mode: Progressing",
        "cn": "升降级模式：进行中",
        "tw": "升降級模式：進行中",
        "jp": "レートモード：進行中",
        "ko": "레이팅 모드: 진행 중",
        "de": "Ranglisten-Modus: Aktiv",
        "es": "Modo clasificatorio: En progreso",
        "fr": "Mode classé: En cours",
        "ru": "Рейтинговый режим: В процессе",
        "tr": "Dereceli Mod: Devam Ediyor",
        "ua": "Рейтинговий режим: Триває",
    },
    "rated_mode_desc": {
        "en": "Net wins tracked for rank update",
        "cn": "净胜局数将用于段位更新",
        "tw": "淨勝局數將用於段位更新",
        "jp": "ランク更新のため勝敗を記録中",
        "ko": "등급 업데이트를 위한 순승 추적 중",
        "de": "Netto-Siege werden für Rang-Update verfolgt",
        "es": "Victorias netas registradas para actualizar rango",
        "fr": "Victoires nettes suivies pour mise à jour du rang",
        "ru": "Чистые победы отслеживаются для обновления ранга",
        "tr": "Derece güncellemesi için net galibiyetler takip ediliyor",
        "ua": "Чисті перемоги відстежуються для оновлення рангу",
    },

    # Game dialogs
    "leave_game_title": {
        "en": "Leave Game?",
        "cn": "离开对局？",
        "tw": "離開對局？",
        "jp": "ゲームを離れますか？",
        "ko": "대국을 떠나시겠습니까?",
        "de": "Spiel verlassen?",
        "es": "¿Abandonar partida?",
        "fr": "Quitter la partie ?",
        "ru": "Покинуть игру?",
        "tr": "Oyundan Çık?",
        "ua": "Покинути гру?",
    },
    "leave_game_warning": {
        "en": "The game is still in progress. Leaving will resign the game. Are you sure?",
        "cn": "对局仍在进行中。离开将自动认输。确定吗？",
        "tw": "對局仍在進行中。離開將自動認輸。確定嗎？",
        "jp": "ゲームはまだ進行中です。離れると投了となります。よろしいですか？",
        "ko": "대국이 진행 중입니다. 나가면 기권 처리됩니다. 확실합니까?",
        "de": "Das Spiel läuft noch. Verlassen bedeutet Aufgabe. Sind Sie sicher?",
        "es": "La partida está en curso. Salir significará rendirse. ¿Estás seguro?",
        "fr": "La partie est en cours. Quitter équivaudra à abandonner. Êtes-vous sûr ?",
        "ru": "Игра еще продолжается. Выход означает сдачу. Вы уверены?",
        "tr": "Oyun hala devam ediyor. Ayrılmak terk etmek anlamına gelir. Emin misiniz?",
        "ua": "Гра ще триває. Вихід означає здачу. Ви впевнені?",
    },
    "resign_and_exit": {
        "en": "Resign & Exit",
        "cn": "认输并退出",
        "tw": "認輸並退出",
        "jp": "投了して終了",
        "ko": "기권 후 나가기",
        "de": "Aufgeben & Beenden",
        "es": "Rendirse y salir",
        "fr": "Abandonner et quitter",
        "ru": "Сдаться и выйти",
        "tr": "Terk Et ve Çık",
        "ua": "Здатися і вийти",
    },
    "resign_game_title": {
        "en": "Resign Game?",
        "cn": "认输？",
        "tw": "認輸？",
        "jp": "投了しますか？",
        "ko": "기권하시겠습니까?",
        "de": "Aufgeben?",
        "es": "¿Rendirse?",
        "fr": "Abandonner ?",
        "ru": "Сдаться?",
        "tr": "Oyunu Terk Et?",
        "ua": "Здатися?",
    },
    "resign_confirm_text": {
        "en": "Are you sure you want to resign?",
        "cn": "确定要认输吗？",
        "tw": "確定要認輸嗎？",
        "jp": "本当に投了しますか？",
        "ko": "정말 기권하시겠습니까?",
        "de": "Sind Sie sicher, dass Sie aufgeben möchten?",
        "es": "¿Estás seguro de que quieres rendirte?",
        "fr": "Êtes-vous sûr de vouloir abandonner ?",
        "ru": "Вы уверены, что хотите сдаться?",
        "tr": "Terk etmek istediğinizden emin misiniz?",
        "ua": "Ви впевнені, що хочете здатися?",
    },
    "play_vs_ai": {
        "en": "Play vs AI",
        "cn": "AI对弈",
        "tw": "AI對弈",
        "jp": "AI対戦",
        "ko": "AI 대국",
        "de": "Gegen KI spielen",
        "es": "Jugar vs IA",
        "fr": "Jouer contre l'IA",
        "ru": "Играть против ИИ",
        "tr": "Yapay Zekaya Karşı Oyna",
        "ua": "Грати проти ШІ",
    },

    # HvH Lobby
    "lobby:title": {
        "en": "Multiplayer Lobby",
        "cn": "多人游戏大厅",
        "tw": "多人遊戲大廳",
        "jp": "マルチプレイヤーロビー",
        "ko": "멀티플레이어 로비",
        "de": "Mehrspieler-Lobby",
        "es": "Sala multijugador",
        "fr": "Salon multijoueur",
        "ru": "Многопользовательское лобби",
        "tr": "Çok Oyunculu Lobi",
        "ua": "Багатокористувацьке лобі",
    },
    "lobby:subtitle": {
        "en": "Play against other humans or watch live games.",
        "cn": "与其他玩家对弈或观看直播对局。",
        "tw": "與其他玩家對弈或觀看直播對局。",
        "jp": "他のプレイヤーと対戦したり、ライブゲームを観戦したりできます。",
        "ko": "다른 플레이어와 대국하거나 실시간 경기를 관전하세요.",
        "de": "Spielen Sie gegen andere Menschen oder schauen Sie Live-Spiele.",
        "es": "Juega contra otros humanos o mira partidas en vivo.",
        "fr": "Jouez contre d'autres humains ou regardez des parties en direct.",
        "ru": "Играйте против других людей или смотрите игры в прямом эфире.",
        "tr": "Diğer insanlara karşı oynayın veya canlı oyunları izleyin.",
        "ua": "Грайте проти інших людей або дивіться ігри наживо.",
    },
    "lobby:quick_match_rated": {
        "en": "Quick Match (Rated)",
        "cn": "快速匹配（排位）",
        "tw": "快速匹配（排位）",
        "jp": "クイックマッチ（レート戦）",
        "ko": "빠른 매칭 (레이팅)",
        "de": "Schnelles Spiel (Rangliste)",
        "es": "Partida rápida (Clasificatoria)",
        "fr": "Match rapide (Classé)",
        "ru": "Быстрый матч (Рейтинговый)",
        "tr": "Hızlı Eşleşme (Dereceli)",
        "ua": "Швидкий матч (Рейтинговий)",
    },
    "lobby:custom_game": {
        "en": "Custom Game",
        "cn": "自定义对局",
        "tw": "自定義對局",
        "jp": "カスタムゲーム",
        "ko": "사용자 정의 대국",
        "de": "Benutzerdefiniertes Spiel",
        "es": "Partida personalizada",
        "fr": "Partie personnalisée",
        "ru": "Пользовательская игра",
        "tr": "Özel Oyun",
        "ua": "Користувацька гра",
    },
    "lobby:online_players": {
        "en": "Online Players",
        "cn": "在线玩家",
        "tw": "在線玩家",
        "jp": "オンラインプレイヤー",
        "ko": "온라인 플레이어",
        "de": "Online-Spieler",
        "es": "Jugadores en línea",
        "fr": "Joueurs en ligne",
        "ru": "Онлайн игроки",
        "tr": "Çevrimiçi Oyuncular",
        "ua": "Онлайн гравці",
    },
    "lobby:active_games": {
        "en": "Active Games",
        "cn": "进行中的对局",
        "tw": "進行中的對局",
        "jp": "進行中のゲーム",
        "ko": "진행 중인 대국",
        "de": "Aktive Spiele",
        "es": "Partidas activas",
        "fr": "Parties actives",
        "ru": "Активные игры",
        "tr": "Aktif Oyunlar",
        "ua": "Активні ігри",
    },
    "lobby:no_active_games": {
        "en": "No active games at the moment.",
        "cn": "当前没有进行中的对局。",
        "tw": "當前沒有進行中的對局。",
        "jp": "現在、進行中のゲームはありません。",
        "ko": "현재 진행 중인 대국이 없습니다.",
        "de": "Momentan keine aktiven Spiele.",
        "es": "No hay partidas activas en este momento.",
        "fr": "Aucune partie active pour le moment.",
        "ru": "В данный момент нет активных игр.",
        "tr": "Şu anda aktif oyun yok.",
        "ua": "На даний момент немає активних ігор.",
    },
    "lobby:active_games_desc": {
        "en": "Games will appear here once matchmaking is functional.",
        "cn": "匹配功能启用后，对局将显示在这里。",
        "tw": "匹配功能啟用後，對局將顯示在這裡。",
        "jp": "マッチメイキングが機能すると、ゲームがここに表示されます。",
        "ko": "매칭 기능이 활성화되면 대국이 여기에 표시됩니다.",
        "de": "Spiele werden hier angezeigt, sobald das Matchmaking funktioniert.",
        "es": "Las partidas aparecerán aquí cuando el emparejamiento esté funcionando.",
        "fr": "Les parties apparaîtront ici une fois le matchmaking fonctionnel.",
        "ru": "Игры появятся здесь, когда заработает поиск соперников.",
        "tr": "Eşleştirme çalıştığında oyunlar burada görünecektir.",
        "ua": "Ігри з'являться тут, коли запрацює пошук суперників.",
    },
    "lobby:finding_opponent": {
        "en": "Finding Opponent...",
        "cn": "正在寻找对手...",
        "tw": "正在尋找對手...",
        "jp": "対戦相手を探しています...",
        "ko": "상대를 찾는 중...",
        "de": "Gegner wird gesucht...",
        "es": "Buscando oponente...",
        "fr": "Recherche d'un adversaire...",
        "ru": "Поиск соперника...",
        "tr": "Rakip Aranıyor...",
        "ua": "Пошук суперника...",
    },
    "lobby:matching_desc": {
        "en": "Looking for a suitable match for you.",
        "cn": "正在为您寻找合适的对手。",
        "tw": "正在為您尋找合適的對手。",
        "jp": "あなたに適した対戦相手を探しています。",
        "ko": "적합한 상대를 찾고 있습니다.",
        "de": "Suche nach einem passenden Gegner für Sie.",
        "es": "Buscando un oponente adecuado para ti.",
        "fr": "Recherche d'un adversaire adapté pour vous.",
        "ru": "Ищем подходящего соперника для вас.",
        "tr": "Sizin için uygun bir eşleşme aranıyor.",
        "ua": "Шукаємо відповідного суперника для вас.",
    },
    "lobby:invite": {
        "en": "Invite",
        "cn": "邀请",
        "tw": "邀請",
        "jp": "招待",
        "ko": "초대",
        "de": "Einladen",
        "es": "Invitar",
        "fr": "Inviter",
        "ru": "Пригласить",
        "tr": "Davet Et",
        "ua": "Запросити",
    },
    "lobby:watch": {
        "en": "Watch",
        "cn": "观战",
        "tw": "觀戰",
        "jp": "観戦",
        "ko": "관전",
        "de": "Zuschauen",
        "es": "Ver",
        "fr": "Regarder",
        "ru": "Смотреть",
        "tr": "İzle",
        "ua": "Дивитись",
    },
    "lobby:you": {
        "en": "You",
        "cn": "你",
        "tw": "你",
        "jp": "あなた",
        "ko": "당신",
        "de": "Sie",
        "es": "Tú",
        "fr": "Vous",
        "ru": "Вы",
        "tr": "Siz",
        "ua": "Ви",
    },
    "lobby:no_players": {
        "en": "No other players online.",
        "cn": "没有其他在线玩家。",
        "tw": "沒有其他在線玩家。",
        "jp": "他にオンラインのプレイヤーはいません。",
        "ko": "다른 온라인 플레이어가 없습니다.",
        "de": "Keine anderen Spieler online.",
        "es": "No hay otros jugadores en línea.",
        "fr": "Aucun autre joueur en ligne.",
        "ru": "Нет других игроков онлайн.",
        "tr": "Başka çevrimiçi oyuncu yok.",
        "ua": "Немає інших гравців онлайн.",
    },
    "lobby:no_rank": {
        "en": "No Rank",
        "cn": "无段位",
        "tw": "無段位",
        "jp": "ランクなし",
        "ko": "등급 없음",
        "de": "Kein Rang",
        "es": "Sin rango",
        "fr": "Sans rang",
        "ru": "Без ранга",
        "tr": "Derece Yok",
        "ua": "Без рангу",
    },
    "lobby:invitation_title": {
        "en": "Game Invitation",
        "cn": "对局邀请",
        "tw": "對局邀請",
        "jp": "ゲームへの招待",
        "ko": "대국 초대",
        "de": "Spieleinladung",
        "es": "Invitación de partida",
        "fr": "Invitation à une partie",
        "ru": "Приглашение на игру",
        "tr": "Oyun Daveti",
        "ua": "Запрошення на гру",
    },
    "lobby:invitation_text": {
        "en": "{{name}} invited you to a game.",
        "cn": "{{name}} 邀请你进行对局。",
        "tw": "{{name}} 邀請你進行對局。",
        "jp": "{{name}}さんがゲームに招待しました。",
        "ko": "{{name}}님이 대국에 초대했습니다.",
        "de": "{{name}} hat Sie zu einem Spiel eingeladen.",
        "es": "{{name}} te ha invitado a una partida.",
        "fr": "{{name}} vous a invité à une partie.",
        "ru": "{{name}} пригласил вас на игру.",
        "tr": "{{name}} sizi bir oyuna davet etti.",
        "ua": "{{name}} запросив вас на гру.",
    },
    "lobby:accept": {
        "en": "Accept",
        "cn": "接受",
        "tw": "接受",
        "jp": "承諾",
        "ko": "수락",
        "de": "Annehmen",
        "es": "Aceptar",
        "fr": "Accepter",
        "ru": "Принять",
        "tr": "Kabul Et",
        "ua": "Прийняти",
    },
    "lobby:decline": {
        "en": "Decline",
        "cn": "拒绝",
        "tw": "拒絕",
        "jp": "辞退",
        "ko": "거절",
        "de": "Ablehnen",
        "es": "Rechazar",
        "fr": "Refuser",
        "ru": "Отклонить",
        "tr": "Reddet",
        "ua": "Відхилити",
    },
    "Spectators": {
        "en": "Spectators",
        "cn": "观众",
        "tw": "觀眾",
        "jp": "観戦者",
        "ko": "관전자",
        "de": "Zuschauer",
        "es": "Espectadores",
        "fr": "Spectateurs",
        "ru": "Зрители",
        "tr": "İzleyiciler",
        "ua": "Глядачі",
    },
    "Moves": {
        "en": "Moves",
        "cn": "手数",
        "tw": "手數",
        "jp": "手数",
        "ko": "수",
        "de": "Züge",
        "es": "Movimientos",
        "fr": "Coups",
        "ru": "Ходы",
        "tr": "Hamleler",
        "ua": "Ходи",
    },

    # Friends Panel
    "Friends & Following": {
        "en": "Friends & Following",
        "cn": "好友与关注",
        "tw": "好友與關注",
        "jp": "フレンドとフォロー",
        "ko": "친구 및 팔로잉",
        "de": "Freunde & Gefolgt",
        "es": "Amigos y seguidos",
        "fr": "Amis et abonnements",
        "ru": "Друзья и подписки",
        "tr": "Arkadaşlar ve Takip",
        "ua": "Друзі та підписки",
    },
    "no_friends_desc": {
        "en": "You are not following anyone yet.",
        "cn": "你还没有关注任何人。",
        "tw": "你還沒有關注任何人。",
        "jp": "まだ誰もフォローしていません。",
        "ko": "아직 아무도 팔로우하지 않았습니다.",
        "de": "Sie folgen noch niemandem.",
        "es": "Aún no sigues a nadie.",
        "fr": "Vous ne suivez personne pour l'instant.",
        "ru": "Вы еще ни на кого не подписаны.",
        "tr": "Henüz kimseyi takip etmiyorsunuz.",
        "ua": "Ви ще нікого не відстежуєте.",
    },

    # Game Room specific
    "Game Over": {
        "en": "Game Over",
        "cn": "对局结束",
        "tw": "對局結束",
        "jp": "ゲーム終了",
        "ko": "게임 종료",
        "de": "Spiel beendet",
        "es": "Partida terminada",
        "fr": "Partie terminée",
        "ru": "Игра окончена",
        "tr": "Oyun Bitti",
        "ua": "Гра закінчена",
    },
    "game_room:your_turn": {
        "en": "Your Turn",
        "cn": "轮到你了",
        "tw": "輪到你了",
        "jp": "あなたの番です",
        "ko": "당신의 차례입니다",
        "de": "Sie sind dran",
        "es": "Tu turno",
        "fr": "Votre tour",
        "ru": "Ваш ход",
        "tr": "Sizin Sıranız",
        "ua": "Ваш хід",
    },
    "game_room:opponents_turn": {
        "en": "Opponent's Turn",
        "cn": "对手回合",
        "tw": "對手回合",
        "jp": "相手の番",
        "ko": "상대방의 차례",
        "de": "Gegner ist dran",
        "es": "Turno del oponente",
        "fr": "Tour de l'adversaire",
        "ru": "Ход соперника",
        "tr": "Rakibin Sırası",
        "ua": "Хід суперника",
    },
    "game_room:spectating": {
        "en": "Spectating",
        "cn": "观战中",
        "tw": "觀戰中",
        "jp": "観戦中",
        "ko": "관전 중",
        "de": "Zuschauen",
        "es": "Observando",
        "fr": "Observation",
        "ru": "Наблюдение",
        "tr": "İzleniyor",
        "ua": "Спостереження",
    },
    "game_room:leave": {
        "en": "Leave Game",
        "cn": "离开对局",
        "tw": "離開對局",
        "jp": "ゲームを離れる",
        "ko": "대국 나가기",
        "de": "Spiel verlassen",
        "es": "Salir de la partida",
        "fr": "Quitter la partie",
        "ru": "Покинуть игру",
        "tr": "Oyundan Ayrıl",
        "ua": "Покинути гру",
    },
    "game_room:leave_forfeit": {
        "en": "Leave & Forfeit",
        "cn": "离开并弃权",
        "tw": "離開並棄權",
        "jp": "離れて没収試合",
        "ko": "나가고 기권하기",
        "de": "Verlassen & Aufgeben",
        "es": "Salir y abandonar",
        "fr": "Quitter et abandonner",
        "ru": "Покинуть и сдаться",
        "tr": "Ayrıl ve Pes Et",
        "ua": "Покинути і здатися",
    },
    "game_room:forfeit_warning": {
        "en": "Leaving will forfeit the game. Are you sure?",
        "cn": "离开将导致弃权。确定吗？",
        "tw": "離開將導致棄權。確定嗎？",
        "jp": "離れると没収試合になります。よろしいですか？",
        "ko": "나가면 기권 처리됩니다. 확실합니까?",
        "de": "Verlassen führt zur Aufgabe. Sind Sie sicher?",
        "es": "Salir significará abandonar la partida. ¿Estás seguro?",
        "fr": "Quitter entraînera un forfait. Êtes-vous sûr ?",
        "ru": "Выход приведет к поражению. Вы уверены?",
        "tr": "Ayrılmak oyunu kaybetmenize neden olacak. Emin misiniz?",
        "ua": "Вихід призведе до програшу. Ви впевнені?",
    },
    "game_room:back_to_lobby": {
        "en": "Back to Lobby",
        "cn": "返回大厅",
        "tw": "返回大廳",
        "jp": "ロビーに戻る",
        "ko": "로비로 돌아가기",
        "de": "Zurück zur Lobby",
        "es": "Volver al lobby",
        "fr": "Retour au salon",
        "ru": "Вернуться в лобби",
        "tr": "Lobiye Dön",
        "ua": "Повернутися до лобі",
    },
    "game_end:resign_win": {
        "en": "You won! Opponent resigned.",
        "cn": "你赢了！对手认输。",
        "tw": "你贏了！對手認輸。",
        "jp": "あなたの勝ち！相手が投了しました。",
        "ko": "승리했습니다! 상대가 기권했습니다.",
        "de": "Sie haben gewonnen! Gegner hat aufgegeben.",
        "es": "¡Ganaste! El oponente se rindió.",
        "fr": "Vous avez gagné ! L'adversaire a abandonné.",
        "ru": "Вы выиграли! Соперник сдался.",
        "tr": "Kazandınız! Rakip terk etti.",
        "ua": "Ви виграли! Суперник здався.",
    },
    "game_end:resign_loss": {
        "en": "You resigned.",
        "cn": "你认输了。",
        "tw": "你認輸了。",
        "jp": "あなたが投了しました。",
        "ko": "기권했습니다.",
        "de": "Sie haben aufgegeben.",
        "es": "Te rendiste.",
        "fr": "Vous avez abandonné.",
        "ru": "Вы сдались.",
        "tr": "Terk ettiniz.",
        "ua": "Ви здалися.",
    },
    "game_end:timeout_win": {
        "en": "You won on time!",
        "cn": "你因超时获胜！",
        "tw": "你因超時獲勝！",
        "jp": "時間切れであなたの勝ち！",
        "ko": "시간 초과로 승리했습니다!",
        "de": "Sie haben durch Zeitüberschreitung gewonnen!",
        "es": "¡Ganaste por tiempo!",
        "fr": "Vous avez gagné au temps !",
        "ru": "Вы выиграли по времени!",
        "tr": "Süre aşımı ile kazandınız!",
        "ua": "Ви виграли за часом!",
    },
    "game_end:timeout_loss": {
        "en": "You lost on time.",
        "cn": "你因超时落败。",
        "tw": "你因超時落敗。",
        "jp": "時間切れで負け。",
        "ko": "시간 초과로 패배했습니다.",
        "de": "Sie haben durch Zeitüberschreitung verloren.",
        "es": "Perdiste por tiempo.",
        "fr": "Vous avez perdu au temps.",
        "ru": "Вы проиграли по времени.",
        "tr": "Süre aşımı ile kaybettiniz.",
        "ua": "Ви програли за часом.",
    },
    "game_end:forfeit_win": {
        "en": "You won! Opponent forfeited.",
        "cn": "你赢了！对手弃权。",
        "tw": "你贏了！對手棄權。",
        "jp": "あなたの勝ち！相手が棄権しました。",
        "ko": "승리했습니다! 상대가 기권했습니다.",
        "de": "Sie haben gewonnen! Gegner hat aufgegeben.",
        "es": "¡Ganaste! El oponente abandonó.",
        "fr": "Vous avez gagné ! L'adversaire a abandonné.",
        "ru": "Вы выиграли! Соперник отказался.",
        "tr": "Kazandınız! Rakip pes etti.",
        "ua": "Ви виграли! Суперник відмовився.",
    },
    "game_end:forfeit_loss": {
        "en": "You forfeited the game.",
        "cn": "你弃权了。",
        "tw": "你棄權了。",
        "jp": "あなたが棄権しました。",
        "ko": "기권했습니다.",
        "de": "Sie haben aufgegeben.",
        "es": "Abandonaste la partida.",
        "fr": "Vous avez abandonné la partie.",
        "ru": "Вы отказались от игры.",
        "tr": "Oyunu kaybettiniz.",
        "ua": "Ви відмовилися від гри.",
    },

    # Misc
    "Loading Board...": {
        "en": "Loading Board...",
        "cn": "正在加载棋盘...",
        "tw": "正在載入棋盤...",
        "jp": "盤面を読み込み中...",
        "ko": "바둑판 로딩 중...",
        "de": "Brett wird geladen...",
        "es": "Cargando tablero...",
        "fr": "Chargement du plateau...",
        "ru": "Загрузка доски...",
        "tr": "Tahta Yükleniyor...",
        "ua": "Завантаження дошки...",
    },
    "Analysis": {
        "en": "Analysis",
        "cn": "分析",
        "tw": "分析",
        "jp": "分析",
        "ko": "분석",
        "de": "Analyse",
        "es": "Análisis",
        "fr": "Analyse",
        "ru": "Анализ",
        "tr": "Analiz",
        "ua": "Аналіз",
    },
    "Library": {
        "en": "Library",
        "cn": "棋谱库",
        "tw": "棋譜庫",
        "jp": "ライブラリ",
        "ko": "라이브러리",
        "de": "Bibliothek",
        "es": "Biblioteca",
        "fr": "Bibliothèque",
        "ru": "Библиотека",
        "tr": "Kütüphane",
        "ua": "Бібліотека",
    },
}


def update_po_file(lang_code: str, translations: dict):
    """Update a single .po file with translations."""
    po_path = I18N_DIR / lang_code / "LC_MESSAGES" / "katrain.po"

    if not po_path.exists():
        print(f"  Warning: {po_path} does not exist, skipping...")
        return 0

    po = polib.pofile(str(po_path))
    updated_count = 0

    # Build a lookup of existing entries by msgid
    existing_entries = {entry.msgid: entry for entry in po}

    for msgid, lang_translations in translations.items():
        if lang_code not in lang_translations:
            continue

        msgstr = lang_translations[lang_code]

        if msgid in existing_entries:
            entry = existing_entries[msgid]
            # Only update if different or empty
            if entry.msgstr != msgstr:
                entry.msgstr = msgstr
                updated_count += 1
        else:
            # Add new entry
            new_entry = polib.POEntry(msgid=msgid, msgstr=msgstr)
            po.append(new_entry)
            updated_count += 1

    if updated_count > 0:
        po.save(str(po_path))

    return updated_count


def main():
    """Main function to update all language files."""
    print("=" * 60)
    print("KaTrain Galaxy UI Batch Translation Script")
    print("=" * 60)

    languages = ["en", "cn", "tw", "jp", "ko", "de", "es", "fr", "ru", "tr", "ua"]

    total_updates = 0

    for lang in languages:
        print(f"\nProcessing {lang}...")
        count = update_po_file(lang, GALAXY_TRANSLATIONS)
        print(f"  Updated {count} entries")
        total_updates += count

    print(f"\n{'=' * 60}")
    print(f"Total entries updated across all languages: {total_updates}")
    print("=" * 60)
    print("\nNext steps:")
    print("1. Run 'python i18n.py' to compile .mo files")
    print("2. Run 'cd katrain/web/ui && npm run build' to rebuild frontend")
    print("3. Restart the server to see changes")


if __name__ == "__main__":
    main()
